"""A2A client wiring. Generated by SDLC Accelerators (agentic-ai-adk domain skill).
One RemoteA2aAgent per a2a_agent tool binding.
"""
from google.adk.agents.remote_a2a_agent import RemoteA2aAgent

_A2A = {
    "body-shop-a2a": RemoteA2aAgent(
        name="body-shop-a2a",
        agent_card="a2a://bodyshop-partner.com/agent/v2",
        # auth: mTLS + Agent Card
    ),
}


def get_a2a_agent(name: str):
    return _A2A[name]
