"""FunctionTools generated from app-blueprint.json business_rules[].
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from google.adk.tools import FunctionTool



def _fnol_coordinator_fn_impl(claim: dict) -> dict:
    """Business rules: BR-004
    Source: spec.md §7.
    """
    severity = claim.get("severity", "low")
    flags = []
    # BR-004: IF severity IN ('critical', 'high') THEN route_to_human = true
    # NOTE: rule conditions below are scaffolded from business_rules[].
    # Verify the extracted predicates against spec.md §7 before production.
    # TODO verify predicate for BR-004
    # IF severity IN ('critical', 'high') THEN route_to_human = true
    return {"severity": severity, "flags": flags}


fnol_coordinator_fn = FunctionTool(func=_fnol_coordinator_fn_impl)


def _severity_classifier_fn_impl(claim: dict) -> dict:
    """Business rules: BR-001, BR-002, BR-003, BR-005
    Source: spec.md §7.
    """
    severity = claim.get("severity", "low")
    flags = []
    # BR-001: IF damage_description CONTAINS 'total loss' OR damage_estimate > $15,000 THEN severity = 'critical'
    # BR-002: IF injuries_reported = true THEN severity = MIN('high', current_severity)
    # BR-003: IF police_report_filed = false AND damage_estimate > $5,000 THEN flag = 'fraud_review'
    # BR-005: IF severity >= 'critical' AND damage_estimate > $10,000 THEN delegate_body_shop = true
    # NOTE: rule conditions below are scaffolded from business_rules[].
    # Verify the extracted predicates against spec.md §7 before production.
    # TODO verify predicate for BR-001
    # IF damage_description CONTAINS 'total loss' OR damage_estimate > $15,000 THEN severity = 'critical'
    # TODO verify predicate for BR-002
    # IF injuries_reported = true THEN severity = MIN('high', current_severity)
    # TODO verify predicate for BR-003
    # IF police_report_filed = false AND damage_estimate > $5,000 THEN flag = 'fraud_review'
    # TODO verify predicate for BR-005
    # IF severity >= 'critical' AND damage_estimate > $10,000 THEN delegate_body_shop = true
    return {"severity": severity, "flags": flags}


severity_classifier_fn = FunctionTool(func=_severity_classifier_fn_impl)

