"""MCP client wiring. Generated by SDLC Accelerators (agentic-ai-adk domain skill).
One MCPToolset per mcp_server tool binding.
"""
from google.adk.tools.mcp_tool import MCPToolset, StdioConnectionParams

_TOOLSETS = {
    "claims-db-mcp": MCPToolset(
        connection_params=StdioConnectionParams(
            url="mcp://claims-db.company.internal:8443",
            auth="OAuth 2.1 + Workload Identity",
        ),
    ),
    "policy-api-mcp": MCPToolset(
        connection_params=StdioConnectionParams(
            url="mcp://policy-api.company.internal:8443",
            auth="OAuth 2.1 + mTLS",
        ),
    ),
    "vehicle-api-mcp": MCPToolset(
        connection_params=StdioConnectionParams(
            url="mcp://vehicle-api.company.internal:8443",
            auth="OAuth 2.1 + mTLS",
        ),
    ),
    "weather-api-mcp": MCPToolset(
        connection_params=StdioConnectionParams(
            url="mcp://weather-api.external.com:443",
            auth="API Key (Secret Manager)",
        ),
    ),
    "review-queue-mcp": MCPToolset(
        connection_params=StdioConnectionParams(
            url="mcp://review-queue.company.internal:8443",
            auth="OAuth 2.1 + Workload Identity",
        ),
    ),
}


def get_mcp_toolset(name: str) -> MCPToolset:
    return _TOOLSETS[name]
