"""Agent Identity — per-agent least-privilege config.
Generated by SDLC Accelerators (agentic-ai-adk domain skill) from agent_identity_config[].
"""
AGENT_IDENTITY = {
    "contract_review_loop": {
        "service_account": "sa-contract-loop@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["delegation-only"],
        "denied": ["doc-store-mcp", "legal-review-a2a", "compliance-engine-a2a"],
        "delegation": ["review_chain"],
    },
    "extract_clauses": {
        "service_account": "sa-extract-clauses@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["doc-store-mcp:read", "clause_parser_fn:invoke"],
        "denied": [],
        "delegation": [],
    },
    "legal_risk": {
        "service_account": "sa-legal-risk@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["legal-review-a2a:invoke"],
        "denied": [],
        "delegation": [],
    },
    "compliance_risk": {
        "service_account": "sa-compliance-risk@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["compliance-engine-a2a:invoke"],
        "denied": [],
        "delegation": [],
    },
    "synthesize_report": {
        "service_account": "sa-synthesize@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["report_builder_fn:invoke"],
        "denied": [],
        "delegation": [],
    },
}
