"""compliance_risk — Compliance risk via partner
Generated by SDLC Accelerators (agentic-ai-adk domain skill). Do not edit by hand;
edit spec.md/plan.md and re-run /accelerator.generate.
"""
from google.adk.agents import LlmAgent
from opentelemetry import trace

from tools.a2a_clients import get_a2a_agent
from callbacks.model_armor import (
    screen_input,
)

_tracer = trace.get_tracer("compliance_risk")


def build_compliance_risk() -> LlmAgent:
    """Construct the compliance_risk agent with its tools, identity, and screening."""
    agent = LlmAgent(
        name="compliance_risk",
        model="gemini-2.0-flash",
        description="Compliance risk via partner",
        tools=[
            get_a2a_agent("compliance-engine-a2a"),
        ],
        before_model_callback=screen_input,
    )

    return agent

