"""contract_review_loop — Iterative refinement until quality threshold
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
LoopAgent node: iterates its single sub-agent until termination.
"""
from google.adk.agents import LoopAgent

from agents.review_chain import build_review_chain


def build_contract_review_loop() -> LoopAgent:
    """Iterative refinement until quality threshold"""
    return LoopAgent(
        name="contract_review_loop",
        description="Iterative refinement until quality threshold",
        max_iterations=5,
        sub_agents=[
            build_review_chain(),
        ],
    )
