"""extract_clauses — Extract contract clauses
Generated by SDLC Accelerators (agentic-ai-adk domain skill). Do not edit by hand;
edit spec.md/plan.md and re-run /accelerator.generate.
"""
from google.adk.agents import LlmAgent
from opentelemetry import trace

from tools.mcp_clients import get_mcp_toolset
from tools.function_tools import clause_parser_fn
from callbacks.model_armor import (
    screen_input,
)

_tracer = trace.get_tracer("extract_clauses")


def build_extract_clauses() -> LlmAgent:
    """Construct the extract_clauses agent with its tools, identity, and screening."""
    agent = LlmAgent(
        name="extract_clauses",
        model="gemini-2.0-flash",
        description="Extract contract clauses",
        tools=[
            get_mcp_toolset("doc-store-mcp"),
            clause_parser_fn,
        ],
        before_model_callback=screen_input,
    )

    return agent

