"""legal_risk — Legal risk via partner
Generated by SDLC Accelerators (agentic-ai-adk domain skill). Do not edit by hand;
edit spec.md/plan.md and re-run /accelerator.generate.
"""
from google.adk.agents import LlmAgent
from opentelemetry import trace

from tools.a2a_clients import get_a2a_agent
from callbacks.model_armor import (
    screen_input,
)

_tracer = trace.get_tracer("legal_risk")


def build_legal_risk() -> LlmAgent:
    """Construct the legal_risk agent with its tools, identity, and screening."""
    agent = LlmAgent(
        name="legal_risk",
        model="gemini-2.0-flash",
        description="Legal risk via partner",
        tools=[
            get_a2a_agent("legal-review-a2a"),
        ],
        before_model_callback=screen_input,
    )

    return agent

