"""parallel_risk — Concurrent legal + compliance risk assessment
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from google.adk.agents import ParallelAgent

from agents.legal_risk import build_legal_risk
from agents.compliance_risk import build_compliance_risk


def build_parallel_risk() -> ParallelAgent:
    """Concurrent legal + compliance risk assessment — concurrent fan-out."""
    return ParallelAgent(
        name="parallel_risk",
        description="Concurrent legal + compliance risk assessment",
        sub_agents=[
            build_legal_risk(),
            build_compliance_risk(),
        ],
    )
