"""review_chain — Extract -> assess -> synthesize
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from google.adk.agents import SequentialAgent

from agents.extract_clauses import build_extract_clauses
from agents.parallel_risk import build_parallel_risk
from agents.synthesize_report import build_synthesize_report


def build_review_chain() -> SequentialAgent:
    """Root orchestrator. Extract -> assess -> synthesize
    Identity: delegation-only (holds no tools directly).
    """
    return SequentialAgent(
        name="review_chain",
        description="Extract -> assess -> synthesize",
        sub_agents=[
            build_extract_clauses(),
            build_parallel_risk(),
            build_synthesize_report(),
        ],
    )
