"""synthesize_report — Synthesize final risk report
Generated by SDLC Accelerators (agentic-ai-adk domain skill). Do not edit by hand;
edit spec.md/plan.md and re-run /accelerator.generate.
"""
from google.adk.agents import LlmAgent
from opentelemetry import trace

from tools.function_tools import report_builder_fn
from callbacks.model_armor import (
    screen_input,
    screen_output,
)

_tracer = trace.get_tracer("synthesize_report")


def build_synthesize_report() -> LlmAgent:
    """Construct the synthesize_report agent with its tools, identity, and screening."""
    agent = LlmAgent(
        name="synthesize_report",
        model="gemini-2.0-flash",
        description="Synthesize final risk report",
        tools=[
            report_builder_fn,
        ],
        before_model_callback=screen_input,
        after_model_callback=screen_output,
    )

    return agent

