"""Phase B — deterministic composition of the canonical brownfield spec.md (NO LLM in the fusion path).

Two composers live here:

  * compose_spec(epic, registry, resolved, ...) — the Epic-to-Spec fusion path. Renders a
    specify-conformant spec.md from the Epic's modernization intent (scope table, dispositions, AWS
    targets, AC, NFRs) fused with CSA ground truth (component current-state + the 8-signal integration
    inventory). Sections, in order: Application Summary, Modernization Scope (in/out/unresolved),
    per-component modernization units, the CSA-sourced Integration Inventory (so the SAME validate_spec
    gate scores it and `/speckit.plan` consumes it unchanged), and NFRs.

  * map_ledger_to_spec(ledger) — the legacy extractive fallback used when no CSA architecture.md is
    present; renders the integration inventory directly from the span-grounded Epic Signal Ledger.

Deterministic: same inputs -> identical spec.md. Component sections precede the Integration Inventory so
the integration-block parser (spec_parser) only ever sees integration field lines.
"""

from __future__ import annotations

from typing import Any

from brownfield.ingest.csa_loader import CsaRegistry
from brownfield.ingest.epic_models import (
    SCOPE_SCHEMA,
    SIGNAL_KEYS,
    SIGNAL_LABEL,
    BrownfieldEpicSignalLedger,
    Epic,
    EpicProvenance,
)
from brownfield.ingest.fusion import ResolvedScope

CLARIFY = "[NEEDS CLARIFICATION]"

# Current-state attributes we expect the CSA architecture.md to carry per component.
_EXPECTED_COMP_ATTRS = ["technology", "hosting", "data store", "dependencies"]

_MIGRATION_NOTE = {
    "Refactor": (
        "Re-architect into AWS-native services. Define new service/API boundaries, externalize "
        "session/state, and plan data migration to the managed target. Use a strangler-fig path so the "
        "legacy component is decommissioned incrementally as functionality moves."
    ),
    "Rehost": (
        "Lift-and-shift to AWS with minimal code change. Containerize or image the component "
        "(AMI / ECS), remap networking and identity (Entra ID -> IAM/SSO), and re-point its "
        "integrations. Defer re-architecture; record it as tech-debt for a later Refactor."
    ),
}


def _provenance_header(prov: EpicProvenance, csa_hash: str, mode: str) -> str:
    ov = prov.object_version if prov.object_version is not None else "unknown"
    csa = csa_hash or "none"
    return (
        f"<!-- Generated by: /accelerator.epic-to-spec ({mode}) -->\n"
        f"<!-- Source: Rally Epic `{prov.formatted_id}` @ ObjectVersion `{ov}`; "
        f"CSA architecture.md @ `{csa}` -->\n"
        f"<!-- Provenance is duplicated in modernization-scope-ledger.json "
        f"(durable sidecar for staleness checks against BOTH the Epic and the CSA). -->\n"
        f"> Canonical brownfield modernization spec generated from Rally Epic `{prov.formatted_id}` "
        f"(ObjectVersion `{ov}`) fused with the CSA architecture (`{csa}`). This is the final spec — "
        f"`/speckit.plan` follows directly. Review {CLARIFY} fields before planning.\n"
    )


def _scope_section(epic: Epic, registry: CsaRegistry, rs: ResolvedScope) -> list[str]:
    out = ["## Modernization Scope", ""]
    out.append("| Component | Name | Disposition | AWS Target | Rationale |")
    out.append("|-----------|------|-------------|-----------|-----------|")
    for u in rs.in_scope:
        disp = u.disposition or f"{CLARIFY} (unrecognized disposition)"
        out.append(
            f"| {u.component_id} | {u.component.name or CLARIFY} | {disp} "
            f"| {u.scope.aws_target or CLARIFY} | {u.scope.rationale or '—'} |"
        )
    out.append("")
    if rs.out_of_scope:
        names = ", ".join(
            f"{cid} ({registry.components[cid].name})" for cid in rs.out_of_scope
        )
        out.append(f"**Explicitly out of scope (remain as-is):** {names}")
        out.append("")
    if rs.unresolved:
        out.append(
            f"**{CLARIFY} — Epic names components not present in the CSA:** "
            f"{', '.join(rs.unresolved)}. These cannot be modernized until the CSA architecture.md "
            "is corrected or the Epic scope is fixed."
        )
        out.append("")
    return out


def _component_section(u: Any) -> str:
    comp = u.component
    disp = u.disposition or CLARIFY
    lines = [
        f"### Component: {comp.component_id} — {comp.name or CLARIFY} (Disposition: {disp})"
    ]
    lines.append("")
    lines.append("**Current state (from CSA):**")
    if comp.attributes:
        for label, value in comp.attributes.items():
            lines.append(f"- {label.capitalize()}: {value}")
    else:
        lines.append(
            f"- {CLARIFY} — component not described in the CSA architecture.md"
        )
    lines.append("")
    lines.append(f"**Target state:** {u.scope.aws_target or CLARIFY}")
    if u.scope.rationale:
        lines.append(f"**Rationale:** {u.scope.rationale}")
    note = _MIGRATION_NOTE.get(u.disposition or "", "")
    if note:
        lines.append(f"**Migration considerations ({disp}):** {note}")
    else:
        lines.append(
            f"**Migration considerations:** {CLARIFY} — disposition must be Refactor or Rehost."
        )
    return "\n".join(lines)


def _integration_block(ig: Any) -> str:
    """Render one CSA integration as an 8-signal block parseable by spec_parser/validate_spec."""
    lines = [f"### Integration: {ig.int_id} — {ig.name or CLARIFY}"]
    for k in SIGNAL_KEYS:
        lines.append(f"- **{SIGNAL_LABEL[k]}:** {ig.signals.get(k) or CLARIFY}")
    if ig.components:
        lines.append(f"<!-- components: {', '.join(ig.components)} -->")
    return "\n".join(lines)


def compose_spec(
    epic: Epic,
    registry: CsaRegistry,
    rs: ResolvedScope,
    csa_hash: str = "",
) -> tuple[str, dict[str, Any], dict[str, Any]]:
    """Fusion composer. Returns (spec_md, per_component_confidence, modernization_scope_ledger)."""
    prov = epic.provenance(csa_hash=csa_hash or registry.content_hash)
    app = (epic.name or registry.app_summary or epic.formatted_id).strip()
    out = [_provenance_header(prov, csa_hash or registry.content_hash, "fusion"), ""]
    out += [f"# Brownfield Modernization Spec — {app}", ""]

    out += ["## Application Summary", ""]
    out += [registry.app_summary or epic.description.split("\n")[0] or CLARIFY, ""]

    out += _scope_section(epic, registry, rs)

    out += ["## Components in Scope", ""]
    for u in rs.in_scope:
        out.append(_component_section(u))
        out.append("")

    # CSA-sourced integration inventory for the in-scope components (the validate_spec gate reads this).
    integrations = registry.integrations_for(rs.in_scope_ids)
    out += ["## Integration Inventory", ""]
    if integrations:
        for ig in integrations:
            out.append(_integration_block(ig))
            out.append("")
    else:
        out += [
            f"{CLARIFY} — no CSA integrations touch the in-scope components. Confirm the "
            "architecture.md integration inventory and component linkage.",
            "",
        ]

    out += ["## Non-Functional Requirements (Application-Wide)"]
    nfrs = [str(n) for n in epic.nfrs if str(n).strip()]
    if nfrs:
        out += [f"- {n}" for n in nfrs]
    else:
        out.append(f"- {CLARIFY}")

    if epic.acceptance_criteria:
        out += ["", "## Acceptance Criteria"]
        out += [f"- {a}" for a in epic.acceptance_criteria if str(a).strip()]

    spec_md = "\n".join(out).rstrip() + "\n"

    per_component_confidence = {
        u.component_id: round(
            sum(1 for a in _EXPECTED_COMP_ATTRS if u.component.attributes.get(a))
            / len(_EXPECTED_COMP_ATTRS),
            2,
        )
        for u in rs.in_scope
    }
    scope_ledger = {
        "schema": SCOPE_SCHEMA,
        "provenance": prov.to_dict(),
        "resolved_scope": rs.to_dict(),
        "integrations": [ig.to_dict() for ig in integrations],
        "per_component_confidence": per_component_confidence,
    }
    return spec_md, per_component_confidence, scope_ledger


# ----------------------------------------------------------------------------------------------------
# Legacy extractive fallback (no CSA architecture.md present) — renders the integration inventory from
# the span-grounded Epic Signal Ledger. Kept so `/speckit.specify`-less ingestion still works when a CSA
# has not yet been produced; the developer is told to supply the CSA or fall back to /speckit.specify.
# ----------------------------------------------------------------------------------------------------
def _field(ig: Any, key: str) -> str:
    return (ig.fields.get(key) or {}).get("value") or CLARIFY


def _render_legacy_integration(ig: Any) -> str:
    shown = min(ig.filled, len(SIGNAL_KEYS))
    over = "+" if ig.filled > len(SIGNAL_KEYS) else ""
    lines = [f"### Integration: {ig.int_id} — {ig.name or CLARIFY}"]
    for k in SIGNAL_KEYS:
        lines.append(f"- **{SIGNAL_LABEL[k]}:** {_field(ig, k)}")
    target = (ig.target_intent or {}).get("value")
    lines.append(f"- **Target intent:** {target or CLARIFY}")
    lines.append(
        f"<!-- confidence {ig.confidence:.2f} (filled {shown}{over}/{len(SIGNAL_KEYS)}) -->"
    )
    return "\n".join(lines)


def map_ledger_to_spec(
    led: BrownfieldEpicSignalLedger,
) -> tuple[str, dict[str, Any]]:
    """Legacy: render spec.md (str) + per-integration confidence from the ledger. Deterministic."""
    name = (led.summary.get("value") or "").split(".")[0].strip() or (
        led.provenance.formatted_id
    )
    out = [
        _provenance_header(
            led.provenance, led.provenance.csa_hash, "legacy-extractive"
        ),
        "",
        f"# Brownfield Migration Spec — {name}",
        "",
    ]
    out += ["## Application Summary", led.summary.get("value") or CLARIFY, ""]
    out += ["## Modernization Scope", led.scope.get("value") or CLARIFY, ""]
    out += [
        "> No CSA architecture.md was supplied — this spec was extracted from the Epic alone. "
        "Provide the CSA for component-scoped dispositions, or refine via /speckit.specify.",
        "",
    ]
    out += ["## Integration Inventory", ""]
    if led.integrations:
        for ig in led.integrations:
            out.append(_render_legacy_integration(ig))
            out.append("")
    else:
        out += [
            f"{CLARIFY} — no integrations were extractable from the Epic; supply the CSA "
            "architecture.md or add the inventory via /speckit.specify.",
            "",
        ]
    out += ["## Non-Functional Requirements (Application-Wide)"]
    if led.nfrs:
        out += [f"- {n['value']}" for n in led.nfrs]
    else:
        out.append(f"- {CLARIFY}")
    spec_md = "\n".join(out).rstrip() + "\n"
    return spec_md, led.per_integration_confidence()
