"""Phase B — brownfield deterministic mapping (NO LLM).

Renders the integration-keyed Brownfield Epic Signal Ledger into a `spec.md` that conforms to the
brownfield spec template and parses cleanly via `brownfield.spec_parser` (so the same `validate_spec`
gate the blueprint uses can score it). Stamps Rally provenance (FormattedID + ObjectVersion), per-
integration fill-ratio confidence, and `[NEEDS CLARIFICATION]` markers for missing signal fields.
Deterministic: same ledger → identical spec.md.
"""

from __future__ import annotations

from typing import Any

from brownfield.ingest.epic_models import (
    SIGNAL_KEYS,
    SIGNAL_LABEL,
    BrownfieldEpicSignalLedger,
)

CLARIFY = "[NEEDS CLARIFICATION]"


def _field(ig: Any, key: str) -> str:
    return (ig.fields.get(key) or {}).get("value") or CLARIFY


def _provenance_header(led: BrownfieldEpicSignalLedger) -> str:
    p = led.provenance
    ov = p.object_version if p.object_version is not None else "unknown"
    return (
        f"<!-- Generated by: ingest_epic (Brownfield Epic-to-Spec front door) -->\n"
        f"<!-- Source: Rally Epic `{p.formatted_id}` @ ObjectVersion `{ov}` -->\n"
        f"<!-- Provenance is duplicated in epic-signal-ledger.json (durable sidecar for staleness checks). -->\n"
        f"> Signal-bearing brownfield migration spec generated from Rally Epic `{p.formatted_id}` "
        f"(ObjectVersion `{ov}`). Review {CLARIFY} fields and low-confidence integrations before `/plan`.\n"
        f"<!-- M-1 format contract: this is the CANONICAL 8-signal migration-readiness template "
        f"(parsed by spec_parser + scored by validate_spec). `/speckit.specify`'s csa-extractor "
        f"up-converts it into the richer Current-State integration inventory, reconciled against the "
        f"authoritative CSA diagram. -->\n"
    )


def _render_integration(ig: Any) -> str:
    shown = min(ig.filled, len(SIGNAL_KEYS))
    over = "+" if ig.filled > len(SIGNAL_KEYS) else ""
    lines = [f"### Integration: {ig.int_id} — {ig.name or CLARIFY}"]
    for k in SIGNAL_KEYS:
        lines.append(f"- **{SIGNAL_LABEL[k]}:** {_field(ig, k)}")
    target = (ig.target_intent or {}).get("value")
    lines.append(f"- **Target intent:** {target or CLARIFY}")
    lines.append(
        f"<!-- confidence {ig.confidence:.2f} (filled {shown}{over}/{len(SIGNAL_KEYS)}) -->"
    )
    return "\n".join(lines)


def map_ledger_to_spec(led: BrownfieldEpicSignalLedger) -> tuple[str, dict[str, Any]]:
    """Render spec.md (str) + per-integration confidence (dict). Deterministic."""
    name = (led.summary.get("value") or "").split(".")[
        0
    ].strip() or led.provenance.formatted_id
    out = [_provenance_header(led), "", f"# Brownfield Migration Spec — {name}", ""]
    out += ["## Application Summary", led.summary.get("value") or CLARIFY, ""]
    out += ["## Modernization Scope", led.scope.get("value") or CLARIFY, ""]
    out += ["## Integration Inventory", ""]
    if led.integrations:
        for ig in led.integrations:
            out.append(_render_integration(ig))
            out.append("")
    else:
        out += [
            f"{CLARIFY} — no integrations were extractable from the Epic; add the integration "
            "inventory during `/specify` review.",
            "",
        ]
    out += ["## Non-Functional Requirements (Application-Wide)"]
    if led.nfrs:
        out += [f"- {n['value']}" for n in led.nfrs]
    else:
        out.append(f"- {CLARIFY}")
    spec_md = "\n".join(out).rstrip() + "\n"
    return spec_md, led.per_integration_confidence()
