# Per-agent Workload Identity service accounts.
# Constitution Rule 10: each agent gets ONLY the bindings for its assigned tools.
# Orchestrators (delegation-only) get NO direct data access.
# Generated by SDLC Accelerators (agentic-ai-adk domain skill).


# fnol_coordinator (orchestrator — delegation only, no data access)

module "sa_fnol_coordinator" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-fnol-coordinator"
  display_name = "Agent SA — fnol_coordinator"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "claims-db-mcp",
    "policy-api-mcp",
    "vehicle-api-mcp",
    "weather-api-mcp",
    "review-queue-mcp",
    "body-shop-a2a",
  ]
}

# extract_details

module "sa_extract_details" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-extract-details"
  display_name = "Agent SA — extract_details"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "claims-db-mcp:read",
    "claims-db-mcp:write",
    "coverage_calculator_fn:invoke",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "policy-api-mcp",
    "vehicle-api-mcp",
    "weather-api-mcp",
    "review-queue-mcp",
    "body-shop-a2a",
  ]
}

# enrich_policy

module "sa_enrich_policy" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-enrich-policy"
  display_name = "Agent SA — enrich_policy"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "policy-api-mcp:read",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "claims-db-mcp",
    "vehicle-api-mcp",
    "weather-api-mcp",
    "review-queue-mcp",
    "body-shop-a2a",
  ]
}

# enrich_vehicle

module "sa_enrich_vehicle" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-enrich-vehicle"
  display_name = "Agent SA — enrich_vehicle"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "vehicle-api-mcp:read",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "claims-db-mcp",
    "policy-api-mcp",
    "weather-api-mcp",
    "review-queue-mcp",
    "body-shop-a2a",
  ]
}

# enrich_weather

module "sa_enrich_weather" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-enrich-weather"
  display_name = "Agent SA — enrich_weather"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "weather-api-mcp:read",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "claims-db-mcp",
    "policy-api-mcp",
    "vehicle-api-mcp",
    "review-queue-mcp",
    "body-shop-a2a",
  ]
}

# severity_classifier

module "sa_severity_classifier" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-severity-classifier"
  display_name = "Agent SA — severity_classifier"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "severity_classifier_fn:invoke",
    "body-shop-a2a:estimate",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "claims-db-mcp",
    "policy-api-mcp",
    "vehicle-api-mcp",
    "weather-api-mcp",
    "review-queue-mcp",
  ]
}

# human_review

module "sa_human_review" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-human-review"
  display_name = "Agent SA — human_review"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "review-queue-mcp:read",
    "review-queue-mcp:write",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "claims-db-mcp",
    "policy-api-mcp",
    "vehicle-api-mcp",
    "weather-api-mcp",
    "body-shop-a2a",
  ]
}

