# Terraform for fnol-claims-agent
# Generated by SDLC Accelerators (agentic-ai-adk domain skill).
# Constitution Rule 4: company modules ONLY — never raw google_*/aws_* resources.
# Constitution Rules 8-10: VPC-SC + CMEK + per-agent Workload Identity enforced by the modules.

terraform {
  required_version = ">= 1.5"
  required_providers {
    google = { source = "hashicorp/google", version = "~> 5.0" }
  }
}

variable "project_id" { type = string }
variable "env"        { type = string }


module "tf_cloud_run_agent" {
  source  = "github.com/company/tf-cloud-run-agent"
  version = "v2.1.0"
  region = "us-east1"
  min_instances = 1
  max_instances = 20
  cmek_key = "projects/PROJECT/locations/us-east1/keyRings/agents/cryptoKeys/cloud-run"
}

module "tf_apigee_gateway" {
  source  = "github.com/company/tf-apigee-gateway"
  version = "v1.8.0"
  environment = "prod"
  rate_limit = "500/hour"
}

module "tf_cloud_sql" {
  source  = "github.com/company/tf-cloud-sql"
  version = "v3.0.0"
  region = "us-east1"
  tier = "db-custom-4-16384"
  ha_enabled = True
  read_replica_region = "us-west1"
  cmek_key = "projects/PROJECT/locations/us-east1/keyRings/data/cryptoKeys/cloud-sql"
}

module "tf_pilot_cold" {
  source  = "github.com/company/tf-pilot-cold"
  version = "v1.2.0"
  primary_region = "us-east1"
  dr_region = "us-west1"
  rto_target_minutes = 60
  rpo_target_hours = 1
}

