"""enrich_vehicle — Vehicle history enrichment with retry
Generated by SDLC Accelerators (agentic-ai-adk domain skill). Do not edit by hand;
edit spec.md/plan.md and re-run /accelerator.generate.
"""
from google.adk.agents import LlmAgent
from google.adk.agents import LoopAgent
from opentelemetry import trace

from tools.mcp_clients import get_mcp_toolset
from callbacks.model_armor import (
    screen_input,
)

_tracer = trace.get_tracer("enrich_vehicle")


def build_enrich_vehicle() -> LoopAgent:
    """Construct the enrich_vehicle agent with its tools, identity, and screening."""
    agent = LlmAgent(
        name="enrich_vehicle",
        model="gemini-2.0-flash",
        description="Vehicle history enrichment with retry",
        tools=[
            get_mcp_toolset("vehicle-api-mcp"),
        ],
        before_model_callback=screen_input,
    )

    # Retry policy from app-blueprint.json: LoopAgent, max 3, exponential backoff
    return LoopAgent(
        name="enrich_vehicle_retry",
        sub_agents=[agent],
        max_iterations=3,
    )

