"""extract_details — Extract claimant details from unstructured input
Generated by SDLC Accelerators (agentic-ai-adk domain skill). Do not edit by hand;
edit spec.md/plan.md and re-run /accelerator.generate.
"""
from google.adk.agents import LlmAgent
from opentelemetry import trace

from tools.mcp_clients import get_mcp_toolset
from tools.function_tools import coverage_calculator_fn
from callbacks.model_armor import (
    screen_input,
    screen_output,
)

_tracer = trace.get_tracer("extract_details")


def build_extract_details() -> LlmAgent:
    """Construct the extract_details agent with its tools, identity, and screening."""
    agent = LlmAgent(
        name="extract_details",
        model="gemini-2.0-flash",
        description="Extract claimant details from unstructured input",
        tools=[
            get_mcp_toolset("claims-db-mcp"),
            coverage_calculator_fn,
        ],
        before_model_callback=screen_input,
        after_model_callback=screen_output,
    )

    return agent

