"""fnol_coordinator — Root orchestrator — 4-step sequential chain with parallel sub-step
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from google.adk.agents import SequentialAgent

from agents.extract_details import build_extract_details
from agents.parallel_enrichment import build_parallel_enrichment
from agents.severity_classifier import build_severity_classifier
from agents.human_review import build_human_review


def build_fnol_coordinator() -> SequentialAgent:
    """Root orchestrator. Root orchestrator — 4-step sequential chain with parallel sub-step
    Identity: delegation-only (holds no tools directly).
    """
    return SequentialAgent(
        name="fnol_coordinator",
        description="Root orchestrator — 4-step sequential chain with parallel sub-step",
        sub_agents=[
            build_extract_details(),
            build_parallel_enrichment(),
            build_severity_classifier(),
            build_human_review(),
        ],
    )
