"""human_review — Route high-severity claims to human adjuster (Human-in-the-Loop)
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from typing import AsyncGenerator
from google.adk.agents import BaseAgent
from google.adk.events import Event
from opentelemetry import trace

from tools.mcp_clients import get_mcp_toolset
from callbacks.model_armor import (
    screen_input,
    screen_output,
)

_tracer = trace.get_tracer("human_review")


class HumanReview(BaseAgent):
    """Route high-severity claims to human adjuster
    HITL escalation. Routes qualifying cases to a human via its bound tools:
    review-queue-mcp.
    """

    async def _run_async_impl(self, ctx) -> AsyncGenerator[Event, None]:
        with _tracer.start_as_current_span("human_review"):
            screen_input(ctx, ctx.session.state)
            tool_1 = get_mcp_toolset("review-queue-mcp")
            # HITL: enqueue for human review and yield control until a decision returns.
            # The escalation condition is evaluated upstream; this agent performs the handoff.
            result = {"review_requested": True, "state": dict(ctx.session.state)}
            screen_output(ctx, result)
            yield Event(author=self.name, content=result)


def build_human_review() -> BaseAgent:
    return HumanReview(name="human_review")
