"""parallel_enrichment — Concurrent enrichment from 3 independent sources
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from google.adk.agents import ParallelAgent

from agents.enrich_policy import build_enrich_policy
from agents.enrich_vehicle import build_enrich_vehicle
from agents.enrich_weather import build_enrich_weather


def build_parallel_enrichment() -> ParallelAgent:
    """Concurrent enrichment from 3 independent sources — concurrent fan-out."""
    return ParallelAgent(
        name="parallel_enrichment",
        description="Concurrent enrichment from 3 independent sources",
        sub_agents=[
            build_enrich_policy(),
            build_enrich_vehicle(),
            build_enrich_weather(),
        ],
    )
