"""severity_classifier — Classify claim severity using business rules + A2A delegation
Generated by SDLC Accelerators (agentic-ai-adk domain skill). Do not edit by hand;
edit spec.md/plan.md and re-run /accelerator.generate.
"""
from google.adk.agents import LlmAgent
from opentelemetry import trace

from tools.a2a_clients import get_a2a_agent
from tools.function_tools import severity_classifier_fn
from callbacks.model_armor import (
    screen_input,
    screen_output,
)

_tracer = trace.get_tracer("severity_classifier")


def build_severity_classifier() -> LlmAgent:
    """Construct the severity_classifier agent with its tools, identity, and screening."""
    agent = LlmAgent(
        name="severity_classifier",
        model="gemini-2.0-flash",
        description="Classify claim severity using business rules + A2A delegation",
        tools=[
            severity_classifier_fn,
            get_a2a_agent("body-shop-a2a"),
        ],
        before_model_callback=screen_input,
        after_model_callback=screen_output,
    )

    return agent

