"""Runtime entrypoint for .
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from agents.fnol_coordinator import build_fnol_coordinator


def build_root_agent():
    """Build the root agent tree: fnol_coordinator (SequentialAgent)."""
    return build_fnol_coordinator()


root_agent = build_root_agent()
