"""
HA/DR Diagram Generator
=======================
Generates SVG component diagrams and draw.io XML files for every combination
of DR Strategy × Lifecycle Phase (4 strategies × 3 phases = 12 diagrams).

How It Works (high-level flow)
------------------------------
1. The caller passes a list of services (e.g. ["Amazon RDS", "Amazon EC2"]).
2. For each of the 12 (strategy, phase) combos, we look up the expected
   service states in the STATE_MATRIX constant (a big dictionary).
3. Each service is classified as "core" (databases / storage) or
   "non-core" (compute / networking).  Core and non-core services get
   different states depending on the strategy and phase.
4. We build an SVG image and a draw.io XML file that show two regions
   side-by-side (Primary + DR) with every service drawn as a colour-coded
   box matching its state (Active=green, Standby=amber, etc.).
5. The SVG is also converted to PNG for downstream consumers.

Two generation modes
---------------------
- **Programmatic** (default — ``use_ai_diagrams=False``):
  Everything is built from templates in pure Python.  Zero Gemini API calls,
  completes in under 1 second, output is always valid.
- **AI** (opt-in — ``use_ai_diagrams=True``):
  SVG is generated by Gemini for more creative layouts.  draw.io XML is
  still built programmatically because the AI version added no value.

Artefacts produced per diagram
-------------------------------
- SVG  → embeddable in HTML / SharePoint pages
- PNG  → fallback raster image (via svglib or cairosvg)
- draw.io XML → stored on GCS so architects can edit later

Public entry-points
--------------------
- ``generate_all_diagrams()``   — synchronous
- ``agenerate_all_diagrams()``  — async (parallelises AI calls)
"""

import asyncio
import io
import json
import logging
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional, Tuple

import vertexai
from vertexai.generative_models import GenerativeModel, GenerationConfig

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────────────
# Data classes — these are simple containers that group related data together.
# Think of them like named tuples or structs in other languages.
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class DiagramArtifact:
    """
    Holds all output files for ONE diagram (one DR strategy + one lifecycle phase).

    Example: "Warm Standby / Failover" produces one DiagramArtifact with
    an SVG string, a draw.io XML string, a PNG byte array, and a description.
    """
    dr_strategy: str                  # e.g. "Warm Standby"
    lifecycle_phase: str              # e.g. "Failover"
    svg_content: str = ""             # raw SVG markup (embeddable in HTML)
    drawio_xml: str = ""              # draw.io XML (editable in draw.io app)
    png_bytes: bytes = b""            # raster PNG image bytes
    description: str = ""             # human-readable description of the phase
    is_fallback: bool = False         # True if we had to use a placeholder


@dataclass
class PatternDiagramBundle:
    """
    Container for ALL 12 diagrams of a single pattern.

    The diagrams dict is keyed by (strategy, phase) tuples—so you can look up
    any specific combination like bundle.get("Warm Standby", "Failover").
    """
    pattern_name: str
    diagrams: Dict[Tuple[str, str], DiagramArtifact] = field(default_factory=dict)

    def get(self, strategy: str, phase: str) -> Optional[DiagramArtifact]:
        """Look up a single diagram by strategy + phase.  Returns None if missing."""
        return self.diagrams.get((strategy, phase))

    def all_artifacts(self) -> List[DiagramArtifact]:
        """Return a flat list of every DiagramArtifact in the bundle."""
        return list(self.diagrams.values())


@dataclass
class RegionStates:
    """
    Describes what state each service category should be in for a given
    (DR strategy, lifecycle phase) pair.

    We split services into two categories:
     - "core" = databases & storage (stateful, hard to move)
     - "non-core" = compute & networking (stateless, easy to recreate)

    Each category has a separate state in the Primary and DR regions because
    core and non-core services often behave differently during failover.
    For example, in "Pilot Light On Demand / Initial Provisioning":
     - core services in DR are in Standby (database replica running)
     - non-core services in DR are Not-Deployed (no compute provisioned yet)
    """
    primary_core: str       # State of data/storage services in primary region
    primary_non_core: str   # State of compute/network services in primary region
    dr_core: str            # State of data/storage services in DR region
    dr_non_core: str        # State of compute/network services in DR region
    arrow_label: str        # Label on the arrow between regions (e.g. "Async Replication")


# ──────────────────────────────────────────────────────────────────────────────
# Constants
#
# These define the universe of DR strategies and lifecycle phases we support.
# Every combination of strategy × phase produces one diagram.
# ──────────────────────────────────────────────────────────────────────────────

# The four DR strategies, ordered from cheapest/slowest recovery to most
# expensive/fastest recovery:
DR_STRATEGIES = [
    "Backup and Restore",        # Cheapest — restore from backups (hours RTO)
    "Pilot Light On Demand",     # Core DB replica running; compute spun up on demand
    "Pilot Light Cold Standby",  # Core DB + compute deployed but stopped
    "Warm Standby",              # Everything running at reduced scale (minutes RTO)
]

# The three lifecycle phases every DR strategy goes through:
LIFECYCLE_PHASES = [
    "Initial Provisioning",  # Normal operations — primary active, DR in standby
    "Failover",              # Primary down — DR region takes over
    "Failback",              # Primary restored — traffic moves back from DR
]

# Colour palette for service states.  Every service box in the diagram is
# filled with the colour matching its current state.
STATE_COLORS = {
    "Active":       "#4CAF50",  # green  — service is live and serving traffic
    "Standby":      "#FF9800",  # amber  — running but not serving traffic
    "Scaled-Down":  "#03A9F4",  # blue   — running at reduced capacity
    "Not-Deployed": "#9E9E9E",  # grey   — not provisioned at all
    "Restoring":    "#E91E63",  # pink   — being restored from backup
    "Syncing":      "#9C27B0",  # purple — data syncing between regions
}

# ──────────────────────────────────────────────────────────────────────────────
# STATE_MATRIX — the heart of deterministic diagram generation
#
# This dictionary is the single source of truth for what every diagram looks
# like.  Given a (DR strategy, lifecycle phase) pair, it tells us:
#   - What state core services are in (Primary region + DR region)
#   - What state non-core services are in (Primary region + DR region)
#   - What label to put on the arrow connecting the two regions
#
# "Core" services = databases & storage (stateful, e.g. RDS, S3)
# "Non-core" services = compute & networking (stateless, e.g. EC2, Lambda)
#
# Example reading:
#   ("Warm Standby", "Failover") → RegionStates(
#       primary_core="Not-Deployed",    # primary DB is down
#       primary_non_core="Not-Deployed", # primary compute is down
#       dr_core="Active",                # DR DB promoted to active
#       dr_non_core="Active",            # DR compute scaled up to full
#       arrow_label="Scale Up + DNS Failover"
#   )
# ──────────────────────────────────────────────────────────────────────────────

STATE_MATRIX: Dict[Tuple[str, str], RegionStates] = {
    # ── Backup and Restore ────────────────────────────────────────────────
    ("Backup and Restore", "Initial Provisioning"): RegionStates(
        "Active", "Active", "Not-Deployed", "Not-Deployed",
        "Scheduled Backup \u2192 Cross-Region Storage"),
    ("Backup and Restore", "Failover"): RegionStates(
        "Not-Deployed", "Not-Deployed", "Restoring", "Restoring",
        "Restore from Backup"),
    ("Backup and Restore", "Failback"): RegionStates(
        "Syncing", "Syncing", "Active", "Active",
        "Data Sync DR \u2192 Primary"),
    # ── Pilot Light On Demand ─────────────────────────────────────────────
    ("Pilot Light On Demand", "Initial Provisioning"): RegionStates(
        "Active", "Active", "Standby", "Not-Deployed",
        "Async Replication"),
    ("Pilot Light On Demand", "Failover"): RegionStates(
        "Not-Deployed", "Not-Deployed", "Active", "Restoring",
        "Promote Replica"),
    ("Pilot Light On Demand", "Failback"): RegionStates(
        "Syncing", "Syncing", "Active", "Active",
        "Data Sync DR \u2192 Primary"),
    # ── Pilot Light Cold Standby ──────────────────────────────────────────
    ("Pilot Light Cold Standby", "Initial Provisioning"): RegionStates(
        "Active", "Active", "Standby", "Scaled-Down",
        "Async Replication"),
    ("Pilot Light Cold Standby", "Failover"): RegionStates(
        "Not-Deployed", "Not-Deployed", "Active", "Active",
        "Start + Promote"),
    ("Pilot Light Cold Standby", "Failback"): RegionStates(
        "Syncing", "Syncing", "Active", "Active",
        "Data Sync DR \u2192 Primary"),
    # ── Warm Standby ──────────────────────────────────────────────────────
    ("Warm Standby", "Initial Provisioning"): RegionStates(
        "Active", "Active", "Standby", "Scaled-Down",
        "Active Replication"),
    ("Warm Standby", "Failover"): RegionStates(
        "Not-Deployed", "Not-Deployed", "Active", "Active",
        "Scale Up + DNS Failover"),
    ("Warm Standby", "Failback"): RegionStates(
        "Syncing", "Syncing", "Active", "Active",
        "Data Sync DR \u2192 Primary"),
}

# ──────────────────────────────────────────────────────────────────────────────
# Service classification: core (stateful) vs. non-core (stateless)
#
# This matters because during a DR event, databases and storage services
# behave very differently from compute services.  A database might be in
# "Standby" (replica running) while compute is "Not-Deployed" (nothing
# provisioned at all).  We use simple keyword matching on the service name
# to decide which category it falls into.
# ──────────────────────────────────────────────────────────────────────────────

# Keywords that identify a service as "core" (stateful data layer).
# If ANY of these substrings appear in the service name, it's core.
# Everything else is classified as "non-core" (compute / network / messaging).
_CORE_SERVICE_KEYWORDS = frozenset({
    "rds", "aurora", "dynamodb", "elasticache", "neptune", "redshift",
    "sql", "spanner", "firestore", "bigtable", "bigquery", "memorystore",
    "s3", "efs", "ebs", "storage", "persistent disk", "filestore",
})


def _is_data_service(service_name: str) -> bool:
    """
    Return True if the service holds persistent state (database / storage).

    Examples:
        _is_data_service("Amazon RDS")  → True   (contains "rds")
        _is_data_service("Amazon EC2")  → False  (no keyword match)
    """
    lower = service_name.lower()
    return any(kw in lower for kw in _CORE_SERVICE_KEYWORDS)

# ──────────────────────────────────────────────────────────────────────────────
# draw.io icon shape mapping  (AWS 4.0 + GCP shape libraries)
#
# draw.io supports official AWS and GCP icon shapes.  When we generate the
# draw.io XML, we want each service box to show the real cloud icon (e.g. the
# RDS database icon) instead of a plain rectangle.
#
# This dictionary maps service names → draw.io "style" fragments that render
# the official icon.  If a service isn't in this dict, we fall back to a
# plain rounded rectangle.
#
# Library references (built into draw.io ≥ 20.x):
#   AWS:  mxgraph.aws4.*
#   GCP:  mxgraph.gcp2.*
# ──────────────────────────────────────────────────────────────────────────────

DRAWIO_SERVICE_ICONS: Dict[str, str] = {
    # ── AWS Services ──────────────────────────────────────────────────────
    # Compute
    "AWS Lambda":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.lambda;",
    "Amazon ECS":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.ecs;",
    "Amazon EKS":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.eks;",
    "Amazon EC2":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.ec2;",
    "AWS Fargate":             "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.fargate;",
    "AWS Step Functions":      "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.step_functions;",
    "AWS Batch":               "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.batch;",
    # Database
    "Amazon RDS":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.rds;",
    "Amazon DynamoDB":         "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.dynamodb;",
    "Amazon Aurora":           "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.aurora;",
    "Amazon ElastiCache":      "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.elasticache;",
    "Amazon Neptune":          "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.neptune;",
    "Amazon Redshift":         "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.redshift;",
    # Storage
    "Amazon S3":               "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.s3;",
    "Amazon EFS":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.elastic_file_system;",
    "Amazon EBS":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.elastic_block_store;",
    # Networking
    "Amazon VPC":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.vpc;",
    "Amazon CloudFront":       "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.cloudfront;",
    "Amazon Route 53":         "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.route_53;",
    "Elastic Load Balancer":   "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.elastic_load_balancing;",
    "Amazon API Gateway":      "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.api_gateway;",
    "AWS Global Accelerator":  "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.global_accelerator;",
    # Messaging
    "Amazon SQS":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.sqs;",
    "Amazon SNS":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.sns;",
    "Amazon EventBridge":      "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.eventbridge;",
    "Amazon Kinesis":          "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.kinesis;",
    # Security & Management
    "AWS KMS":                 "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.key_management_service;",
    "AWS Secrets Manager":     "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.secrets_manager;",
    "AWS IAM":                 "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.identity_and_access_management;",
    "AWS WAF":                 "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.waf;",
    "AWS CloudWatch":          "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.cloudwatch;",
    "AWS CloudTrail":          "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.cloudtrail;",
    # CI/CD
    "AWS CodePipeline":        "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.codepipeline;",
    "Amazon ECR":              "shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.ecr;",

    # ── GCP Services ─────────────────────────────────────────────────────
    # Compute
    "Cloud Run":               "shape=mxgraph.gcp2.cloud_run;",
    "Cloud Functions":         "shape=mxgraph.gcp2.cloud_functions;",
    "Compute Engine":          "shape=mxgraph.gcp2.compute_engine;",
    "Google Kubernetes Engine": "shape=mxgraph.gcp2.google_kubernetes_engine;",
    "GKE":                     "shape=mxgraph.gcp2.google_kubernetes_engine;",
    "App Engine":              "shape=mxgraph.gcp2.app_engine;",
    # Database
    "Cloud SQL":               "shape=mxgraph.gcp2.cloud_sql;",
    "Cloud Spanner":           "shape=mxgraph.gcp2.cloud_spanner;",
    "Firestore":               "shape=mxgraph.gcp2.cloud_firestore;",
    "Cloud Bigtable":          "shape=mxgraph.gcp2.cloud_bigtable;",
    "BigQuery":                "shape=mxgraph.gcp2.bigquery;",
    "Memorystore":             "shape=mxgraph.gcp2.cloud_memorystore;",
    # Storage
    "Cloud Storage":           "shape=mxgraph.gcp2.cloud_storage;",
    "Persistent Disk":         "shape=mxgraph.gcp2.persistent_disk;",
    "Filestore":               "shape=mxgraph.gcp2.filestore;",
    # Networking
    "Cloud CDN":               "shape=mxgraph.gcp2.cloud_cdn;",
    "Cloud DNS":               "shape=mxgraph.gcp2.cloud_dns;",
    "Cloud Load Balancing":    "shape=mxgraph.gcp2.cloud_load_balancing;",
    "Cloud Armor":             "shape=mxgraph.gcp2.cloud_armor;",
    "Cloud VPN":               "shape=mxgraph.gcp2.cloud_vpn;",
    "Cloud Interconnect":      "shape=mxgraph.gcp2.cloud_interconnect;",
    # Messaging
    "Cloud Pub/Sub":           "shape=mxgraph.gcp2.cloud_pubsub;",
    "Pub/Sub":                 "shape=mxgraph.gcp2.cloud_pubsub;",
    "Cloud Tasks":             "shape=mxgraph.gcp2.cloud_tasks;",
    "Eventarc":                "shape=mxgraph.gcp2.eventarc;",
    # Security & Management
    "Cloud KMS":               "shape=mxgraph.gcp2.cloud_key_management_service;",
    "Secret Manager":          "shape=mxgraph.gcp2.secret_manager;",
    "Cloud IAM":               "shape=mxgraph.gcp2.cloud_iam;",
    "Cloud Monitoring":        "shape=mxgraph.gcp2.cloud_monitoring;",
    "Cloud Logging":           "shape=mxgraph.gcp2.cloud_logging;",
    # CI/CD
    "Cloud Build":             "shape=mxgraph.gcp2.cloud_build;",
    "Artifact Registry":       "shape=mxgraph.gcp2.artifact_registry;",
    "Cloud Deploy":            "shape=mxgraph.gcp2.cloud_deploy;",
}

# Pre-built case-insensitive version of the icon dict so lookups are fast
# and case doesn't matter (e.g. "amazon rds" matches "Amazon RDS").
_ICON_LOOKUP: Dict[str, str] = {k.lower(): v for k, v in DRAWIO_SERVICE_ICONS.items()}


def get_drawio_icon_style(service_name: str) -> str:
    """
    Return the draw.io style fragment for a service, or "" if not found.

    Used by _build_programmatic_drawio() to render official cloud icons.
    """
    return _ICON_LOOKUP.get(service_name.lower(), "")

# ──────────────────────────────────────────────────────────────────────────────
# One-shot SVG example for the LLM prompt (AI mode only)
#
# When use_ai_diagrams=True, we include this example SVG in the prompt so
# Gemini understands the expected format.  In programmatic mode (the default),
# this constant is never used — it's only here for the AI code path.
# ──────────────────────────────────────────────────────────────────────────────
SVG_ONE_SHOT_EXAMPLE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500" width="800" height="500">
  <defs>
    <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto">
      <polygon points="0 0, 10 3.5, 0 7" fill="#333"/>
    </marker>
  </defs>
  <style>
    text { font-family: Arial, sans-serif; font-size: 13px; }
    .title { font-size: 18px; font-weight: bold; }
    .region-label { font-size: 15px; font-weight: bold; fill: #333; }
    .svc-label { font-size: 12px; fill: #fff; }
    .state-label { font-size: 11px; font-style: italic; }
  </style>
  <!-- Title -->
  <text x="400" y="30" text-anchor="middle" class="title">Backup and Restore — Initial Provisioning</text>
  <!-- Primary Region -->
  <rect x="30" y="50" width="350" height="400" rx="12" fill="#E3F2FD" stroke="#1565C0" stroke-width="2"/>
  <text x="205" y="80" text-anchor="middle" class="region-label">Primary Region</text>
  <!-- Service box -->
  <rect x="60" y="100" width="140" height="50" rx="8" fill="#4CAF50"/>
  <text x="130" y="130" text-anchor="middle" class="svc-label">Amazon RDS</text>
  <text x="130" y="160" text-anchor="middle" class="state-label" fill="#388E3C">Active</text>
  <!-- DR Region -->
  <rect x="420" y="50" width="350" height="400" rx="12" fill="#FFF3E0" stroke="#E65100" stroke-width="2"/>
  <text x="595" y="80" text-anchor="middle" class="region-label">DR Region</text>
  <rect x="450" y="100" width="140" height="50" rx="8" fill="#9E9E9E"/>
  <text x="520" y="130" text-anchor="middle" class="svc-label">Amazon RDS</text>
  <text x="520" y="160" text-anchor="middle" class="state-label" fill="#616161">Not-Deployed</text>
  <!-- Arrow -->
  <line x1="200" y1="125" x2="445" y2="125" stroke="#333" stroke-width="1.5" marker-end="url(#arrowhead)"/>
</svg>"""


# ──────────────────────────────────────────────────────────────────────────────
# Generator class
# ──────────────────────────────────────────────────────────────────────────────

class HADRDiagramGenerator:
    """
    Main class for generating HA/DR architecture diagrams.

    Produces SVG + draw.io XML + PNG for every (strategy × phase) combination.

    Usage (typical — programmatic mode, no AI):
        generator = HADRDiagramGenerator(project_id="my-gcp-project")
        bundle = generator.generate_all_diagrams(
            pattern_name="My Pattern",
            services=["Amazon RDS", "Amazon EC2", "Amazon S3"],
            hadr_text_sections={"Warm Standby": "...markdown..."},
            pattern_context={"title": "My Pattern"},
        )
        # bundle.diagrams has 12 DiagramArtifact entries

    Key design decisions:
     - draw.io XML is ALWAYS programmatic (deterministic, fast, reliable).
     - SVG is programmatic by default; AI is opt-in via use_ai_diagrams=True.
     - The STATE_MATRIX constant (module level) drives all state assignments.
    """

    def __init__(
        self,
        project_id: str,
        location: str = "us-central1",
        use_ai_diagrams: bool = False,
        ai_model_name: str = "gemini-2.0-flash",
    ):
        """
        Args:
            project_id:       GCP project ID for Vertex AI.
            location:         GCP region.
            use_ai_diagrams:  When False (default), generates diagrams
                              programmatically — zero Gemini calls, zero
                              tokens, completes in < 1 second.  Set to True
                              to use AI for creative SVG layouts at the cost
                              of speed and tokens.
            ai_model_name:    Model to use when ``use_ai_diagrams=True``.
                              Defaults to ``gemini-2.0-flash`` (fast/cheap).
                              Change to ``gemini-2.5-pro`` only if quality
                              matters more than speed.
        """
        self.project_id = project_id
        self.location = location
        self.use_ai_diagrams = use_ai_diagrams
        self.ai_model_name = ai_model_name
        if self.use_ai_diagrams:
            self._init_model()
        else:
            self.model = None
            logger.info(
                "HADRDiagramGenerator initialised in programmatic mode "
                "(zero AI calls)"
            )

    def _init_model(self):
        try:
            vertexai.init(project=self.project_id, location=self.location)
            self.model = GenerativeModel(
                self.ai_model_name,
                system_instruction=(
                    "You are a Principal Cloud Architect and technical "
                    "illustrator. You generate accurate, clean SVG component "
                    "diagrams and draw.io XML files for enterprise HA/DR "
                    "architectures."
                ),
            )
            logger.info(
                f"HADRDiagramGenerator model initialised ({self.ai_model_name})"
            )
        except Exception as e:
            logger.error(f"Failed to initialise diagram model: {e}")
            self.model = None

    # ─── Public API ──────────────────────────────────────────────────────

    def generate_all_diagrams(
        self,
        pattern_name: str,
        services: List[str],
        hadr_text_sections: Dict[str, str],
        pattern_context: Dict[str, Any],
        service_diagram_descriptions: Optional[Dict[str, Dict[str, List[str]]]] = None,
    ) -> PatternDiagramBundle:
        """
        Synchronous entry-point: generate all 12 diagrams for a pattern.

        Iterates over every (strategy × phase) combination and builds
        a DiagramArtifact for each.  In programmatic mode (default),
        this completes in under 1 second with zero Gemini calls.

        Args:
            pattern_name:       Human-readable pattern title (e.g. "3-Tier Web App").
            services:           List of cloud service names in the pattern
                                (e.g. ["Amazon RDS", "Amazon EC2", "Amazon S3"]).
            hadr_text_sections: Maps DR strategy name → Markdown text generated
                                by the HA/DR documentation generator.  Used to
                                extract per-phase descriptions.
            pattern_context:    Pattern metadata dict (title, solution overview, etc.)
            service_diagram_descriptions:
                (AI mode only) Optional dict of service_name → dr_strategy
                → [descriptions] from ingested HA/DR docs.  Provides
                reference architecture context for the LLM prompt.

        Returns:
            PatternDiagramBundle with up to 12 DiagramArtifact entries.
        """
        bundle = PatternDiagramBundle(pattern_name=pattern_name)

        # Iterate over all 4 strategies × 3 phases = 12 combinations
        for strategy in DR_STRATEGIES:
            strategy_text = hadr_text_sections.get(strategy, "")
            # Split the big strategy Markdown into per-phase text blocks
            phase_texts = self._split_phases(strategy_text)

            # Build reference diagram context for AI prompts (empty string
            # in programmatic mode, but doesn't hurt to compute it)
            strategy_diag_context = self._build_diagram_context(
                service_diagram_descriptions, strategy
            )

            for phase in LIFECYCLE_PHASES:
                phase_text = phase_texts.get(phase, "")
                logger.info(f"Generating diagram: {strategy} / {phase}")

                # This call builds SVG + draw.io + PNG for one combo
                artifact = self._generate_single_diagram(
                    pattern_name=pattern_name,
                    services=services,
                    dr_strategy=strategy,
                    lifecycle_phase=phase,
                    phase_description=phase_text,
                    pattern_context=pattern_context,
                    reference_diagram_descriptions=strategy_diag_context,
                )
                bundle.diagrams[(strategy, phase)] = artifact

        # Log summary
        total = len(bundle.diagrams)
        fallbacks = sum(1 for a in bundle.all_artifacts() if a.is_fallback)
        logger.info(
            f"Generated {total} diagrams for '{pattern_name}' "
            f"({fallbacks} fallbacks)"
        )
        return bundle

    @staticmethod
    def _build_diagram_context(
        service_diagram_descriptions: Optional[Dict[str, Dict[str, List[str]]]],
        strategy: str,
    ) -> str:
        """
        Build a prompt-ready text block from reference diagram descriptions.

        Only used in AI mode.  Takes the descriptions of existing HA/DR
        diagrams from ingested service-level docs and formats them as a
        text block that gets injected into the Gemini prompt.  This gives
        the LLM visual inspiration for layout and labelling.

        Returns an empty string if no descriptions are available (which is
        always the case in programmatic mode).
        """
        if not service_diagram_descriptions:
            return ""
        lines: List[str] = []
        for svc_name, strategy_map in service_diagram_descriptions.items():
            descs = strategy_map.get(strategy, [])
            for d in descs:
                if d:
                    lines.append(f"  - {svc_name}: {d}")
        if not lines:
            return ""
        return (
            "# Reference Service-Level HA/DR Diagrams (from ingested docs)\n"
            "These describe the EXISTING architecture diagrams from the\n"
            "service-level HA/DR documentation. Use them as visual inspiration\n"
            "for the component layout, replication arrows, and state labels\n"
            "in the NEW diagram you are generating.\n"
            + "\n".join(lines)
        )

    # ─── Async public API ────────────────────────────────────────────────

    async def agenerate_all_diagrams(
        self,
        pattern_name: str,
        services: List[str],
        hadr_text_sections: Dict[str, str],
        pattern_context: Dict[str, Any],
        service_diagram_descriptions: Optional[Dict[str, Dict[str, List[str]]]] = None,
        timeout_per_diagram: float = 180.0,
        max_concurrent: int = 6,
    ) -> PatternDiagramBundle:
        """
        Async version of ``generate_all_diagrams`` — generates up to 12
        diagrams.

        **Programmatic mode** (``use_ai_diagrams=False``, the default):
        All 12 diagrams are built synchronously in < 1 second with zero
        Gemini calls.  The semaphore and timeout are not used.

        **AI mode** (``use_ai_diagrams=True``):
        SVG generation is parallelised via ``asyncio.gather`` with a
        ``Semaphore(max_concurrent)`` cap.  draw.io XML is still built
        programmatically (the AI draw.io call was the biggest token sink
        and added no value over the deterministic builder).

        Args:
            pattern_name:         Human-readable pattern title.
            services:             List of canonical service names.
            hadr_text_sections:   DR strategy → generated Markdown text.
            pattern_context:      Pattern metadata.
            service_diagram_descriptions:
                Optional dict of service_name → dr_strategy → [descriptions]
                from ingested service-level HA/DR diagrams.
            timeout_per_diagram:  Max seconds per single diagram when using
                                  AI (default 180, ignored in programmatic mode).
            max_concurrent:       Concurrency cap for AI mode (default 6).

        Returns:
            PatternDiagramBundle with up to 12 DiagramArtifact entries.
        """
        bundle = PatternDiagramBundle(pattern_name=pattern_name)

        # ── Fast path: programmatic (no AI) ──────────────────────────────
        if not self.use_ai_diagrams:
            import time
            t0 = time.monotonic()

            for strategy in DR_STRATEGIES:
                strategy_text = hadr_text_sections.get(strategy, "")
                phase_texts = self._split_phases(strategy_text)
                for phase in LIFECYCLE_PHASES:
                    phase_text = phase_texts.get(phase, "")
                    artifact = self._generate_single_diagram(
                        pattern_name, services, strategy,
                        phase, phase_text, pattern_context,
                    )
                    bundle.diagrams[(strategy, phase)] = artifact

            elapsed = time.monotonic() - t0
            logger.info(
                f"Programmatic generation of {len(bundle.diagrams)} diagrams "
                f"for '{pattern_name}' completed in {elapsed:.2f}s "
                f"(zero AI calls)"
            )
            return bundle

        # ── AI path: semaphore-gated parallel Gemini calls ───────────────
        semaphore = asyncio.Semaphore(max_concurrent)

        def _make_fallback(strategy: str, phase: str, desc: str) -> DiagramArtifact:
            """Build a programmatic fallback when AI generation fails or times out."""
            fb = DiagramArtifact(
                dr_strategy=strategy,
                lifecycle_phase=phase,
                svg_content=self._build_programmatic_svg(strategy, phase, services),
                drawio_xml=self._build_programmatic_drawio(strategy, phase, services),
                is_fallback=True,
                description=desc,
            )
            fb.png_bytes = self._svg_to_png(fb.svg_content)
            return fb

        async def _gen_one(
            strategy: str, phase: str, phase_text: str,
            diag_context: str = "",
        ):
            """Generate one diagram with concurrency limit and timeout."""
            async with semaphore:
                try:
                    # Run the synchronous _generate_single_diagram in a thread
                    # so we don't block the event loop while Gemini responds.
                    coro = asyncio.to_thread(
                        self._generate_single_diagram,
                        pattern_name, services, strategy,
                        phase, phase_text, pattern_context,
                        diag_context,
                    )
                    artifact = await asyncio.wait_for(
                        coro, timeout=timeout_per_diagram
                    )
                    return strategy, phase, artifact
                except asyncio.TimeoutError:
                    logger.error(
                        f"Diagram generation timed-out for {strategy}/{phase}"
                    )
                    return strategy, phase, _make_fallback(strategy, phase, phase_text)
                except Exception as e:
                    logger.error(
                        f"Diagram generation failed for {strategy}/{phase}: {e}"
                    )
                    return strategy, phase, _make_fallback(strategy, phase, phase_text)

        # Build task list for all 12 combinations
        tasks = []
        for strategy in DR_STRATEGIES:
            strategy_text = hadr_text_sections.get(strategy, "")
            phase_texts = self._split_phases(strategy_text)
            ref_diag_context = self._build_diagram_context(
                service_diagram_descriptions, strategy
            )
            for phase in LIFECYCLE_PHASES:
                phase_text = phase_texts.get(phase, "")
                logger.info(f"Scheduling async diagram: {strategy} / {phase}")
                tasks.append(_gen_one(strategy, phase, phase_text, ref_diag_context))

        # Execute all (up to max_concurrent at a time)
        results = await asyncio.gather(*tasks, return_exceptions=False)

        for strategy, phase, artifact in results:
            bundle.diagrams[(strategy, phase)] = artifact

        total = len(bundle.diagrams)
        fallbacks = sum(1 for a in bundle.all_artifacts() if a.is_fallback)
        logger.info(
            f"AI-generated {total} diagrams for '{pattern_name}' "
            f"({fallbacks} fallbacks)"
        )
        return bundle

    # ─── Single diagram generation ───────────────────────────────────────

    def _generate_single_diagram(
        self,
        pattern_name: str,
        services: List[str],
        dr_strategy: str,
        lifecycle_phase: str,
        phase_description: str,
        pattern_context: Dict[str, Any],
        reference_diagram_descriptions: str = "",
    ) -> DiagramArtifact:
        """
        Generate SVG + draw.io XML + PNG for one (strategy, phase) pair.

        This is the core method that produces a single DiagramArtifact.
        It follows this flow:

        1. Build draw.io XML (always programmatic — fast and reliable).
        2. Build SVG:
           - Programmatic mode (default): use _build_programmatic_svg()
           - AI mode (opt-in): ask Gemini, validate, retry once, fall back
             to programmatic if Gemini output is broken.
        3. Convert SVG → PNG for raster image consumers.
        4. Return the completed DiagramArtifact.
        """
        artifact = DiagramArtifact(
            dr_strategy=dr_strategy,
            lifecycle_phase=lifecycle_phase,
        )

        # ── Step 1: draw.io XML is ALWAYS programmatic ──────────────────
        # This was the biggest token/speed win — AI-generated draw.io added
        # no value over the deterministic builder.
        artifact.drawio_xml = self._build_programmatic_drawio(
            dr_strategy, lifecycle_phase, services
        )

        # ── Step 2: Build SVG ────────────────────────────────────────────
        if not self.use_ai_diagrams or not self.model:
            # Programmatic mode (default) — instant, always valid
            artifact.svg_content = self._build_programmatic_svg(
                dr_strategy, lifecycle_phase, services
            )
        else:
            # AI mode (opt-in) — ask Gemini to generate a creative SVG
            svg_content = self._generate_svg(
                pattern_name, services, dr_strategy,
                lifecycle_phase, phase_description, pattern_context,
            )
            # Validate the LLM output (it might be malformed XML)
            valid_svg, svg_content = self._validate_and_fix_svg(svg_content)
            if not valid_svg:
                # First attempt failed — retry with a hint to fix the issues
                logger.warning(
                    f"SVG invalid for {dr_strategy}/{lifecycle_phase}, retrying…"
                )
                svg_content = self._generate_svg(
                    pattern_name, services, dr_strategy,
                    lifecycle_phase, phase_description, pattern_context,
                    retry_hint=(
                        "Previous SVG was malformed. Ensure valid XML "
                        "with xmlns and viewBox."
                    ),
                    reference_diagram_descriptions=reference_diagram_descriptions,
                )
                valid_svg, svg_content = self._validate_and_fix_svg(svg_content)
                if not valid_svg:
                    # Both attempts failed — fall back to programmatic SVG
                    logger.error(
                        f"SVG retry failed for {dr_strategy}/{lifecycle_phase}"
                    )
                    svg_content = self._build_programmatic_svg(
                        dr_strategy, lifecycle_phase, services
                    )
                    artifact.is_fallback = True

            artifact.svg_content = svg_content

        # ── Step 3: Convert SVG → PNG ────────────────────────────────────
        artifact.png_bytes = self._svg_to_png(artifact.svg_content)

        # ── Step 4: Attach the phase description text ────────────────────
        artifact.description = phase_description

        return artifact

    # ─── Programmatic diagram builders (zero AI calls) ───────────────────

    @staticmethod
    def _build_programmatic_svg(
        dr_strategy: str,
        lifecycle_phase: str,
        services: List[str],
    ) -> str:
        """
        Build an SVG component diagram entirely in Python — no Gemini calls.

        The SVG layout looks like this (conceptually):

            ┌─────────────────────────────────────────────────┐
            │          Warm Standby — Failover (title)        │
            │                                                 │
            │  ┌─ Primary Region ──┐   ┌── DR Region ───┐    │
            │  │  [Amazon RDS    ] │──→│  [Amazon RDS  ] │    │
            │  │   Not-Deployed    │   │   Active        │    │
            │  │                   │   │                 │    │
            │  │  [Amazon EC2    ] │──→│  [Amazon EC2  ] │    │
            │  │   Not-Deployed    │   │   Active        │    │
            │  └───────────────────┘   └─────────────────┘    │
            │                                                 │
            │  Legend: ■ Active ■ Standby ■ Scaled-Down ...   │
            └─────────────────────────────────────────────────┘

        We build the SVG by appending XML strings to a list, then joining
        them at the end.  This is faster and simpler than using an XML builder.
        """
        # Look up the expected states for this (strategy, phase) combo.
        # If somehow the combo isn't in the matrix, use safe defaults.
        states = STATE_MATRIX.get(
            (dr_strategy, lifecycle_phase),
            RegionStates("Active", "Active", "Standby", "Standby", "Replication"),
        )

        # ── Calculate layout dimensions ──────────────────────────────────
        n = len(services)
        svc_h = 55                          # vertical pixels per service row
        region_top_pad = 80                 # space above first service (for label)
        region_h = region_top_pad + max(n, 1) * svc_h + 20  # total region height
        canvas_h = max(600, region_h + 130) # ensure room for title + legend

        # We'll collect all SVG elements as strings, then join at the end
        parts: List[str] = []

        # ── SVG header + arrow marker definition ─────────────────────────
        parts.append(
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 900 {canvas_h}" width="900" height="{canvas_h}">'
        )
        # Define a reusable arrowhead marker (the "▸" at the end of dashed lines)
        parts.append(
            '<defs>'
            '<marker id="ah" markerWidth="10" markerHeight="7" '
            'refX="10" refY="3.5" orient="auto">'
            '<polygon points="0 0,10 3.5,0 7" fill="#555"/>'
            '</marker>'
            '</defs>'
        )
        # CSS classes for consistent text styling throughout the diagram
        # .t = title, .rl = region label, .sn = service name,
        # .st = state label, .al = arrow label, .lg = legend text
        parts.append(
            '<style>'
            'text{font-family:Arial,Helvetica,sans-serif}'
            '.t{font-size:17px;font-weight:bold;fill:#222}'
            '.rl{font-size:14px;font-weight:bold;fill:#333}'
            '.sn{font-size:12px;fill:#fff}'
            '.st{font-size:11px;font-style:italic}'
            '.al{font-size:10px;fill:#555}'
            '.lg{font-size:10px;fill:#555}'
            '</style>'
        )

        # ── Background + Title ───────────────────────────────────────────
        parts.append(f'<rect width="900" height="{canvas_h}" fill="#FAFAFA" rx="4"/>')

        title_text = f"{dr_strategy} \u2014 {lifecycle_phase}"
        parts.append(
            f'<text x="450" y="35" text-anchor="middle" class="t">'
            f'{title_text}</text>'
        )

        # ── Region background boxes ──────────────────────────────────────
        # Left side = Primary Region (light blue), Right side = DR Region (light orange)
        parts.append(
            f'<rect x="30" y="55" width="390" height="{region_h}" '
            f'rx="10" fill="#E3F2FD" stroke="#1565C0" stroke-width="1.5"/>'
        )
        parts.append(
            '<text x="225" y="82" text-anchor="middle" class="rl">'
            'Primary Region</text>'
        )
        parts.append(
            f'<rect x="480" y="55" width="390" height="{region_h}" '
            f'rx="10" fill="#FFF3E0" stroke="#E65100" stroke-width="1.5"/>'
        )
        parts.append(
            '<text x="675" y="82" text-anchor="middle" class="rl">'
            'DR Region</text>'
        )

        # ── Service boxes + connecting arrows ────────────────────────────
        # For each service, we draw:
        #   1. A coloured box in the Primary region (left)
        #   2. A coloured box in the DR region (right)
        #   3. A dashed arrow connecting them
        # The colour comes from STATE_COLORS based on the service's state.
        for i, svc in enumerate(services):
            # Classify: is this a database/storage service or compute/network?
            is_core = _is_data_service(svc)
            # Pick the right state based on core vs non-core classification
            p_state = states.primary_core if is_core else states.primary_non_core
            d_state = states.dr_core if is_core else states.dr_non_core
            # Map state names to hex colours
            p_color = STATE_COLORS.get(p_state, "#9E9E9E")
            d_color = STATE_COLORS.get(d_state, "#9E9E9E")

            y = 100 + i * svc_h  # vertical position for this service row

            # Primary region service box (left side)
            parts.append(
                f'<rect x="55" y="{y}" width="170" height="38" '
                f'rx="6" fill="{p_color}"/>'
            )
            parts.append(
                f'<text x="140" y="{y + 24}" text-anchor="middle" '
                f'class="sn">{svc}</text>'
            )
            parts.append(
                f'<text x="140" y="{y + 50}" text-anchor="middle" '
                f'class="st" fill="{p_color}">{p_state}</text>'
            )

            # DR region service box (right side)
            # Make "Not-Deployed" and "Scaled-Down" boxes semi-transparent
            # to visually convey they're inactive
            dr_opacity = ' opacity="0.5"' if d_state in ("Not-Deployed", "Scaled-Down") else ""
            parts.append(
                f'<rect x="505" y="{y}" width="170" height="38" '
                f'rx="6" fill="{d_color}"{dr_opacity}/>'
            )
            parts.append(
                f'<text x="590" y="{y + 24}" text-anchor="middle" '
                f'class="sn">{svc}</text>'
            )
            parts.append(
                f'<text x="590" y="{y + 50}" text-anchor="middle" '
                f'class="st" fill="{d_color}">{d_state}</text>'
            )

            # Dashed arrow connecting Primary → DR for this service
            parts.append(
                f'<line x1="225" y1="{y + 19}" x2="503" y2="{y + 19}" '
                f'stroke="#888" stroke-width="1" stroke-dasharray="4,3" '
                f'marker-end="url(#ah)"/>'
            )

        # Label the arrow in the middle of the diagram (e.g. "Async Replication")
        if n > 0:
            mid_y = 100 + (n // 2) * svc_h + 10
            parts.append(
                f'<text x="364" y="{mid_y}" text-anchor="middle" '
                f'class="al">{states.arrow_label}</text>'
            )

        # ── Legend — shows what each colour means ────────────────────────
        legend_y = region_h + 75
        for j, (state_name, color) in enumerate(STATE_COLORS.items()):
            lx = 30 + j * 145
            parts.append(
                f'<rect x="{lx}" y="{legend_y}" width="12" height="12" '
                f'rx="2" fill="{color}"/>'
            )
            parts.append(
                f'<text x="{lx + 16}" y="{legend_y + 11}" '
                f'class="lg">{state_name}</text>'
            )

        parts.append('</svg>')
        return "\n".join(parts)

    @staticmethod
    def _build_programmatic_drawio(
        dr_strategy: str,
        lifecycle_phase: str,
        services: List[str],
    ) -> str:
        """
        Build draw.io XML entirely in Python — no Gemini calls.

        draw.io uses an XML format called "mxfile" which describes shapes
        (mxCell elements) on a canvas.  This method generates that XML
        with official AWS/GCP cloud icons from the DRAWIO_SERVICE_ICONS
        registry and state-based colouring from STATE_COLORS.

        The generated XML can be opened directly in draw.io (diagrams.net)
        for manual editing by architects.  Output is always valid XML.

        Structure of the generated XML:
          <mxfile>
            <diagram>
              <mxGraphModel>
                <root>
                  <mxCell id="0"/>              ← root node (required by draw.io)
                  <mxCell id="1"/>              ← default parent
                  <mxCell id="2" "Primary"/>    ← Primary Region container
                  <mxCell id="3" "DR"/>         ← DR Region container
                  <mxCell id="10" "RDS"/>       ← service in Primary
                  <mxCell id="11" "Active"/>    ← state badge
                  <mxCell id="12" "RDS"/>       ← service in DR
                  <mxCell id="13" "Standby"/>   ← state badge
                  <mxCell id="14" edge/>        ← connecting arrow
                  ...
                </root>
              </mxGraphModel>
            </diagram>
          </mxfile>
        """
        # Look up expected states for this (strategy, phase) combo
        states = STATE_MATRIX.get(
            (dr_strategy, lifecycle_phase),
            RegionStates("Active", "Active", "Standby", "Standby", "Replication"),
        )

        n = len(services)
        svc_spacing = 90  # vertical pixels between each service
        region_h = 80 + max(n, 1) * svc_spacing + 30  # total region height
        cells: List[str] = []   # we'll collect mxCell XML strings here
        cid = 10                # cell ID counter (IDs 0-3 are reserved for root/regions)

        # For each service, we create 5 mxCell elements:
        #   1. Primary service box (with cloud icon if available)
        #   2. Primary state badge (text label below the box)
        #   3. DR service box (same service, different state/colour)
        #   4. DR state badge
        #   5. Connecting edge (arrow) between Primary ↔ DR
        for i, svc in enumerate(services):
            # Classify service and look up states (same logic as SVG builder)
            is_core = _is_data_service(svc)
            p_state = states.primary_core if is_core else states.primary_non_core
            d_state = states.dr_core if is_core else states.dr_non_core
            p_color = STATE_COLORS.get(p_state, "#9E9E9E")
            d_color = STATE_COLORS.get(d_state, "#9E9E9E")
            y = 100 + i * svc_spacing  # vertical position

            # Try to find an official cloud icon for this service
            icon_style = get_drawio_icon_style(svc)

            # ── Primary service cell ─────────────────────────────────────
            # If we have an official cloud icon, use it (60×60 with icon shape).
            # Otherwise, use a simple coloured rounded rectangle (160×45).
            if icon_style:
                p_style = (
                    f"{icon_style}whiteSpace=wrap;fillColor={p_color};"
                    f"fontColor=#232F3E;strokeColor={p_color};fontStyle=1;"
                    f"fontSize=11;labelPosition=center;"
                    f"verticalLabelPosition=bottom;verticalAlign=top;"
                    f"align=center;"
                )
                w, h = 60, 60   # icon cells are square
            else:
                p_style = (
                    f"rounded=1;whiteSpace=wrap;fillColor={p_color};"
                    f"fontColor=#ffffff;strokeColor=#757575;"
                    f"fontSize=11;fontStyle=1;"
                )
                w, h = 160, 45  # plain rectangles are wider

            # Dim inactive services visually
            p_opacity = "opacity=50;" if p_state in ("Not-Deployed", "Scaled-Down") else ""
            cells.append(
                f'        <mxCell id="{cid}" '
                f'value="{svc}&#10;[{p_state}]" '
                f'style="{p_style}{p_opacity}" vertex="1" parent="1">\n'
                f'          <mxGeometry x="80" y="{y}" '
                f'width="{w}" height="{h}" as="geometry"/>\n'
                f'        </mxCell>'
            )
            p_id = cid  # remember this ID so the edge can reference it
            cid += 1

            # Primary state badge (small text label below the service box)
            cells.append(
                f'        <mxCell id="{cid}" value="{p_state}" '
                f'style="text;fontSize=10;fontStyle=2;'
                f'fontColor={p_color};align=center;" '
                f'vertex="1" parent="1">\n'
                f'          <mxGeometry x="65" y="{y + h + 2}" '
                f'width="90" height="18" as="geometry"/>\n'
                f'        </mxCell>'
            )
            cid += 1

            # ── DR service cell (same logic as Primary, different position) ─
            if icon_style:
                d_style = (
                    f"{icon_style}whiteSpace=wrap;fillColor={d_color};"
                    f"fontColor=#232F3E;strokeColor={d_color};fontStyle=1;"
                    f"fontSize=11;labelPosition=center;"
                    f"verticalLabelPosition=bottom;verticalAlign=top;"
                    f"align=center;"
                )
            else:
                d_style = (
                    f"rounded=1;whiteSpace=wrap;fillColor={d_color};"
                    f"fontColor=#ffffff;strokeColor=#757575;"
                    f"fontSize=11;fontStyle=1;"
                )

            d_opacity = "opacity=50;" if d_state in ("Not-Deployed", "Scaled-Down") else ""
            cells.append(
                f'        <mxCell id="{cid}" '
                f'value="{svc}&#10;[{d_state}]" '
                f'style="{d_style}{d_opacity}" vertex="1" parent="1">\n'
                f'          <mxGeometry x="500" y="{y}" '
                f'width="{w}" height="{h}" as="geometry"/>\n'
                f'        </mxCell>'
            )
            d_id = cid  # remember this ID for the edge target
            cid += 1

            # DR state badge (small text below the DR service box)
            cells.append(
                f'        <mxCell id="{cid}" value="{d_state}" '
                f'style="text;fontSize=10;fontStyle=2;'
                f'fontColor={d_color};align=center;" '
                f'vertex="1" parent="1">\n'
                f'          <mxGeometry x="485" y="{y + h + 2}" '
                f'width="90" height="18" as="geometry"/>\n'
                f'        </mxCell>'
            )
            cid += 1

            # ── Connecting edge (arrow) between Primary ↔ DR ────────────
            # The edge references the Primary cell (source) and DR cell (target)
            # by their IDs, so draw.io knows which boxes to connect.
            cells.append(
                f'        <mxCell id="{cid}" '
                f'value="{states.arrow_label}" '
                f'style="edgeStyle=orthogonalEdgeStyle;'
                f'strokeColor=#666666;fontSize=9;" '
                f'edge="1" source="{p_id}" target="{d_id}" parent="1">\n'
                f'          <mxGeometry relative="1" as="geometry"/>\n'
                f'        </mxCell>'
            )
            cid += 1

        # ── Assemble the final mxfile XML ────────────────────────────────
        # Join all the service cells we built above, then wrap them in the
        # required mxfile/diagram/mxGraphModel/root structure.
        cells_str = "\n".join(cells)
        esc_name = f"{dr_strategy} - {lifecycle_phase}"

        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<mxfile host="draw.io">\n'
            f'  <diagram name="{esc_name}" id="prog1">\n'
            '    <mxGraphModel dx="1200" dy="800" grid="1" '
            'gridSize="10" guides="1">\n'
            '      <root>\n'
            '        <mxCell id="0"/>\n'
            '        <mxCell id="1" parent="0"/>\n'
            '        <mxCell id="2" value="Primary Region" '
            'style="rounded=1;whiteSpace=wrap;fillColor=#dae8fc;'
            'strokeColor=#6c8ebf;fontSize=14;fontStyle=1;'
            'verticalAlign=top;" vertex="1" parent="1">\n'
            f'          <mxGeometry x="30" y="50" width="350" '
            f'height="{region_h}" as="geometry"/>\n'
            '        </mxCell>\n'
            '        <mxCell id="3" value="DR Region" '
            'style="rounded=1;whiteSpace=wrap;fillColor=#fff2cc;'
            'strokeColor=#d6b656;fontSize=14;fontStyle=1;'
            'verticalAlign=top;" vertex="1" parent="1">\n'
            f'          <mxGeometry x="420" y="50" width="350" '
            f'height="{region_h}" as="geometry"/>\n'
            '        </mxCell>\n'
            f'{cells_str}\n'
            '      </root>\n'
            '    </mxGraphModel>\n'
            '  </diagram>\n'
            '</mxfile>'
        )

    # ─── AI SVG generation (opt-in only — not used in default mode) ────

    def _generate_svg(
        self,
        pattern_name: str,
        services: List[str],
        dr_strategy: str,
        lifecycle_phase: str,
        phase_description: str,
        pattern_context: Dict[str, Any],
        retry_hint: str = "",
        reference_diagram_descriptions: str = "",
    ) -> str:
        """
        Ask Gemini to produce an SVG component diagram.

        This method is ONLY called when use_ai_diagrams=True.  It builds a
        detailed prompt with layout rules, a one-shot example, and colour
        palette, then sends it to the Gemini model.  The raw SVG string is
        returned (may be invalid — caller should validate).
        """
        services_list = "\n".join(f"  - {s}" for s in services)
        state_guide = self._state_guide(dr_strategy, lifecycle_phase)

        ref_diag_section = ""
        if reference_diagram_descriptions:
            ref_diag_section = f"""
{reference_diagram_descriptions}

Use the above reference diagram descriptions to guide your layout: which
services appear in which region, how replication arrows flow, and which
components are active vs. standby.  The NEW diagram should reflect the new
pattern's services but follow the same architectural patterns shown in the
references.
"""

        prompt = f"""
Generate a clean, professional SVG component diagram for the following HA/DR scenario.

# Pattern
Name: {pattern_name}
Services:
{services_list}

# DR Strategy: {dr_strategy}
# Lifecycle Phase: {lifecycle_phase}

# Phase Description
{phase_description if phase_description else "(Generate appropriate component states based on the DR strategy and lifecycle phase.)"}

# State Guide
{state_guide}
{ref_diag_section}
# Colour Palette for Service States
{json.dumps(STATE_COLORS, indent=2)}

# Layout Rules
1. Show TWO regions side-by-side: "Primary Region" (left, light-blue background)
   and "DR Region" (right, light-orange background).
2. Inside each region, draw a rounded rectangle for EVERY service in the pattern.
3. Colour each service box using the state colour from the palette above.
4. Below or inside each box, show the service state label (Active, Standby, etc.).
5. Draw arrows between Primary and DR service pairs to show data replication,
   failover direction, or synchronisation — label the arrow with the mechanism
   (e.g., "Cross-Region Replication", "Route 53 Failover", "Backup→Restore").
6. Include a title at the top: "{dr_strategy} — {lifecycle_phase}".
7. Include a legend in the bottom-right corner mapping colours to states.
8. Use viewBox="0 0 900 600" and width="900" height="600".
9. Ensure valid SVG with xmlns="http://www.w3.org/2000/svg".

# One-Shot Example
{SVG_ONE_SHOT_EXAMPLE}

{f"# IMPORTANT: {retry_hint}" if retry_hint else ""}

Output ONLY the raw SVG markup. Do NOT wrap it in markdown code fences.
Start with <svg and end with </svg>.
"""
        try:
            response = self.model.generate_content(
                prompt,
                generation_config=GenerationConfig(
                    temperature=0.2,
                    max_output_tokens=4096,
                ),
            )
            return self._strip_code_fences(response.text.strip())
        except Exception as e:
            logger.error(f"SVG generation failed: {e}")
            return ""



    # ─── SVG validation & auto-fix ──────────────────────────────────────

    @staticmethod
    def _validate_and_fix_svg(svg: str) -> Tuple[bool, str]:
        """
        Validate SVG XML and attempt auto-fixes for common LLM output issues.

        LLMs sometimes produce SVG with problems like:
         - Extra text before the <svg> tag (e.g. "Here is the SVG:")
         - Missing xmlns attribute
         - Missing viewBox attribute
         - Malformed XML

        This method tries to fix the first three and then validates with
        Python's XML parser.

        Returns:
            (is_valid, possibly_fixed_svg) — is_valid is True if the SVG
            parses as valid XML after fixes.
        """
        if not svg or not svg.strip():
            return False, svg

        # Fix 1: Strip any text the LLM put before the <svg> opening tag
        svg_start = svg.find("<svg")
        if svg_start > 0:
            svg = svg[svg_start:]
        # Fix 2: Strip any text after the closing </svg> tag
        svg_end = svg.rfind("</svg>")
        if svg_end > 0:
            svg = svg[: svg_end + len("</svg>")]

        # Fix 3: Ensure the xmlns attribute is present (required for valid SVG)
        if 'xmlns="http://www.w3.org/2000/svg"' not in svg:
            svg = svg.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"', 1)

        # Ensure viewBox exists
        if "viewBox" not in svg:
            svg = svg.replace(
                "<svg",
                '<svg viewBox="0 0 900 600"',
                1,
            )

        try:
            ET.fromstring(svg.encode("utf-8"))
            return True, svg
        except ET.ParseError as e:
            logger.warning(f"SVG parse error: {e}")
            return False, svg

    # ─── SVG → PNG conversion ────────────────────────────────────────────

    @staticmethod
    def _svg_to_png(svg_content: str) -> bytes:
        """
        Convert an SVG string to PNG image bytes.

        Why two approaches?
        SVG→PNG conversion requires a native graphics library (Cairo).
        Different platforms bundle it differently, so we try two approaches:

        1. svglib + reportlab + pycairo  (works on Windows/Mac/Linux)
           - pycairo bundles the native Cairo DLLs
           - We shim cairocffi → pycairo so reportlab can find it
        2. cairosvg  (works on Linux containers where libcairo is installed)

        If both fail, we return empty bytes (the SVG is still usable).
        """
        if not svg_content:
            return b""

        # ── Approach 1: svglib + reportlab (preferred, cross-platform) ───
        try:
            # The pycairo package bundles native Cairo DLLs.  We register it
            # as "cairocffi" in sys.modules so that reportlab's rlPyCairo
            # backend can find it without a separate cairocffi install.
            import cairo as _pycairo          # pycairo (bundles native DLLs)
            import sys as _sys
            if "cairocffi" not in _sys.modules:
                _sys.modules["cairocffi"] = _pycairo

            import tempfile
            import os
            from svglib.svglib import svg2rlg
            from reportlab.graphics import renderPM

            # svglib needs a file on disk, so write SVG to a temp file
            with tempfile.NamedTemporaryFile(
                suffix=".svg", delete=False, mode="w", encoding="utf-8"
            ) as tmp:
                tmp.write(svg_content)
                tmp_path = tmp.name

            try:
                drawing = svg2rlg(tmp_path)
                if drawing is None:
                    raise ValueError("svglib returned None — SVG may be invalid")
                png_bytes = renderPM.drawToString(drawing, fmt="PNG")
                return png_bytes
            finally:
                os.unlink(tmp_path)

        except Exception as svg_err:
            logger.warning(f"svglib SVG→PNG failed ({svg_err}), trying cairosvg…")

        # ── Approach 2: cairosvg (needs native libcairo — works in Linux) ─
        try:
            import cairosvg
            png_bytes = cairosvg.svg2png(
                bytestring=svg_content.encode("utf-8"),
                output_width=900,
                output_height=600,
            )
            return png_bytes
        except ImportError:
            logger.warning(
                "Neither svglib nor cairosvg could convert SVG→PNG. "
                "Install with: pip install svglib reportlab pycairo"
            )
            return b""
        except Exception as e:
            logger.error(f"SVG→PNG conversion failed: {e}")
            return b""

    # ─── Helpers (used by AI and programmatic code paths) ──────────────

    @staticmethod
    def _strip_code_fences(text: str) -> str:
        """
        Remove markdown code fences from LLM output.

        LLMs often wrap their output in ```xml ... ``` or ```svg ... ```
        even when told not to.  This strips those fences so we get clean SVG.
        """
        text = re.sub(r"^```(?:xml|svg|html)?\s*\n?", "", text, flags=re.MULTILINE)
        text = re.sub(r"\n?```\s*$", "", text, flags=re.MULTILINE)
        return text.strip()

    @staticmethod
    def _state_guide(dr_strategy: str, lifecycle_phase: str) -> str:
        """
        Return a human-readable hint about expected service states.

        This is injected into the Gemini prompt (AI mode only) so the LLM
        knows what states to draw.  In programmatic mode, STATE_MATRIX
        provides the same information in a structured form; this is the
        natural-language equivalent for the LLM's benefit.
        """
        guides = {
            ("Backup and Restore", "Initial Provisioning"):
                "Primary: all services Active. DR: all services Not-Deployed. "
                "Backups stored in cross-region storage.",
            ("Backup and Restore", "Failover"):
                "Primary: all services down/unavailable. DR: services being "
                "Restored from backups. Show Restoring state.",
            ("Backup and Restore", "Failback"):
                "DR: services Active. Primary: services being Restored/Syncing "
                "back. Show data sync direction DR→Primary.",
            ("Pilot Light On Demand", "Initial Provisioning"):
                "Primary: all Active. DR: core services (DB, config) in minimal "
                "Standby; compute services Not-Deployed.",
            ("Pilot Light On Demand", "Failover"):
                "Primary: down. DR: core services promoted to Active; compute "
                "services being provisioned (Restoring).",
            ("Pilot Light On Demand", "Failback"):
                "DR: Active. Primary: services being re-provisioned and Syncing.",
            ("Pilot Light Cold Standby", "Initial Provisioning"):
                "Primary: all Active. DR: core services in Cold Standby "
                "(stopped but deployed); compute Not-Deployed or Scaled-Down.",
            ("Pilot Light Cold Standby", "Failover"):
                "Primary: down. DR: core services started → Active; compute "
                "services started → Active. Longer spin-up than Warm Standby.",
            ("Pilot Light Cold Standby", "Failback"):
                "DR: Active. Primary: services being restarted and data Syncing.",
            ("Warm Standby", "Initial Provisioning"):
                "Primary: all Active. DR: all services running at Scaled-Down "
                "capacity (Standby). Active replication in progress.",
            ("Warm Standby", "Failover"):
                "Primary: down. DR: all services scaled UP to Active (full "
                "capacity). DNS/routing switched to DR.",
            ("Warm Standby", "Failback"):
                "DR: Active. Primary: services restarted and Syncing. "
                "Once synced, traffic shifted back to Primary.",
        }
        return guides.get(
            (dr_strategy, lifecycle_phase),
            "Use your best judgement for the expected service states."
        )

    @staticmethod
    def _split_phases(strategy_text: str) -> Dict[str, str]:
        """
        Split a DR strategy Markdown section into per-phase text blocks.

        The input is a big Markdown string for one DR strategy (e.g. all of
        "Warm Standby").  It contains ### headings for each lifecycle phase.
        We split it into a dict like:
            {"Initial Provisioning": "...", "Failover": "...", "Failback": "..."}

        This is needed because each diagram corresponds to one phase, so we
        need the phase-specific text to pass to the AI prompt or store as
        the artifact description.
        """
        result: Dict[str, str] = {}
        if not strategy_text:
            return result

        # Build a regex that matches ### headings containing any phase name.
        # For example: "### Initial Provisioning" or "### Failover"
        phase_names = "|".join(re.escape(p) for p in LIFECYCLE_PHASES)
        pattern = re.compile(
            rf"(###\s*(?:{phase_names}))", re.IGNORECASE
        )
        # re.split with a capturing group keeps the delimiters in the list.
        # Result: [pre_text, heading1, body1, heading2, body2, ...]
        parts = pattern.split(strategy_text)

        # Walk pairs of (heading, body) starting from index 1
        i = 1
        while i < len(parts) - 1:
            heading = parts[i].strip().lstrip("#").strip()
            body = parts[i + 1].strip()
            # Match the heading text back to the canonical phase name
            for phase in LIFECYCLE_PHASES:
                if phase.lower() in heading.lower():
                    result[phase] = body
                    break
            i += 2

        return result

    # ─── Fallback generators ─────────────────────────────────────────────

    @staticmethod
    def _fallback_svg(
        dr_strategy: str, lifecycle_phase: str, services: List[str]
    ) -> str:
        """
        Generate a minimal grey placeholder SVG when all else fails.

        This is the last resort — used only when both AI generation AND
        programmatic SVG somehow fail.  It shows service names in grey
        boxes with a note that the diagram should be recreated manually.
        """
        svc_boxes = []
        y = 120
        for svc in services[:8]:  # cap at 8 to fit
            svc_boxes.append(
                f'  <rect x="60" y="{y}" width="280" height="40" rx="6" fill="#BDBDBD"/>\n'
                f'  <text x="200" y="{y + 25}" text-anchor="middle" '
                f'font-family="Arial" font-size="12" fill="#fff">{svc}</text>'
            )
            y += 55
        boxes_str = "\n".join(svc_boxes)

        return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 600" width="900" height="600">
  <rect width="900" height="600" fill="#FAFAFA" rx="4"/>
  <text x="450" y="40" text-anchor="middle" font-family="Arial" font-size="18" font-weight="bold" fill="#333">
    {dr_strategy} — {lifecycle_phase}
  </text>
  <text x="450" y="70" text-anchor="middle" font-family="Arial" font-size="13" fill="#999">
    (Placeholder — diagram generation failed; please recreate in draw.io)
  </text>
  <rect x="30" y="90" width="400" height="{y - 60}" rx="10" fill="#E3F2FD" stroke="#1565C0" stroke-width="1.5"/>
  <text x="230" y="112" text-anchor="middle" font-family="Arial" font-size="14" font-weight="bold" fill="#333">Primary Region</text>
{boxes_str}
  <rect x="470" y="90" width="400" height="{y - 60}" rx="10" fill="#FFF3E0" stroke="#E65100" stroke-width="1.5"/>
  <text x="670" y="112" text-anchor="middle" font-family="Arial" font-size="14" font-weight="bold" fill="#333">DR Region</text>
</svg>"""


