"""Agent Identity — per-agent least-privilege config.
Generated by SDLC Accelerators (agentic-ai-adk domain skill) from agent_identity_config[].
"""
AGENT_IDENTITY = {
    "fnol_coordinator": {
        "service_account": "sa-fnol-coordinator@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["delegation-only"],
        "denied": ["claims-db-mcp", "policy-api-mcp", "vehicle-api-mcp", "weather-api-mcp", "review-queue-mcp", "body-shop-a2a"],
        "delegation": ["extract_details", "parallel_enrichment", "severity_classifier", "human_review"],
    },
    "extract_details": {
        "service_account": "sa-extract-details@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["claims-db-mcp:read", "claims-db-mcp:write", "coverage_calculator_fn:invoke"],
        "denied": ["policy-api-mcp", "vehicle-api-mcp", "weather-api-mcp", "review-queue-mcp", "body-shop-a2a"],
        "delegation": [],
    },
    "enrich_policy": {
        "service_account": "sa-enrich-policy@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["policy-api-mcp:read"],
        "denied": ["claims-db-mcp", "vehicle-api-mcp", "weather-api-mcp", "review-queue-mcp", "body-shop-a2a"],
        "delegation": [],
    },
    "enrich_vehicle": {
        "service_account": "sa-enrich-vehicle@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["vehicle-api-mcp:read"],
        "denied": ["claims-db-mcp", "policy-api-mcp", "weather-api-mcp", "review-queue-mcp", "body-shop-a2a"],
        "delegation": [],
    },
    "enrich_weather": {
        "service_account": "sa-enrich-weather@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["weather-api-mcp:read"],
        "denied": ["claims-db-mcp", "policy-api-mcp", "vehicle-api-mcp", "review-queue-mcp", "body-shop-a2a"],
        "delegation": [],
    },
    "severity_classifier": {
        "service_account": "sa-severity-classifier@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["severity_classifier_fn:invoke", "body-shop-a2a:estimate"],
        "denied": ["claims-db-mcp", "policy-api-mcp", "vehicle-api-mcp", "weather-api-mcp", "review-queue-mcp"],
        "delegation": [],
    },
    "human_review": {
        "service_account": "sa-human-review@PROJECT.iam.gserviceaccount.com",
        "capabilities": ["review-queue-mcp:read", "review-queue-mcp:write"],
        "denied": ["claims-db-mcp", "policy-api-mcp", "vehicle-api-mcp", "weather-api-mcp", "body-shop-a2a"],
        "delegation": [],
    },
}
