"""A2A client wiring. Generated by SDLC Accelerators (agentic-ai-adk domain skill).
One RemoteA2aAgent per a2a_agent tool binding.
"""
from google.adk.agents.remote_a2a_agent import RemoteA2aAgent

_A2A = {
    "legal-review-a2a": RemoteA2aAgent(
        name="legal-review-a2a",
        agent_card="https://legal-review.partner.example/a2a",
        # auth: mTLS + OAuth
    ),
    "compliance-engine-a2a": RemoteA2aAgent(
        name="compliance-engine-a2a",
        agent_card="https://compliance.partner.example/a2a",
        # auth: mTLS + OAuth
    ),
}


def get_a2a_agent(name: str):
    return _A2A[name]
