"""MCP client wiring. Generated by SDLC Accelerators (agentic-ai-adk domain skill).
One MCPToolset per mcp_server tool binding.
"""
from google.adk.tools.mcp_tool import MCPToolset, StdioConnectionParams

_TOOLSETS = {
    "doc-store-mcp": MCPToolset(
        connection_params=StdioConnectionParams(
            url="mcp://doc-store.company.internal:8443",
            auth="OAuth 2.1 + Workload Identity",
        ),
    ),
}


def get_mcp_toolset(name: str) -> MCPToolset:
    return _TOOLSETS[name]
