"""Runtime entrypoint for .
Generated by SDLC Accelerators (agentic-ai-adk domain skill).
"""
from agents.contract_review_loop import build_contract_review_loop


def build_root_agent():
    """Build the root agent tree: contract_review_loop (LoopAgent)."""
    return build_contract_review_loop()


root_agent = build_root_agent()
