"""Phase B — deterministic mapping (Epic Signal Ledger → signal-bearing spec.md).

NO LLM. Renders the 10-section spec.md from the ledger, computes per-section confidence from the signal
slot FILL RATIO (LedgerSection.confidence), and stamps Rally provenance (FormattedID + ObjectVersion)
into the spec header. Empty sections get a `[NEEDS CLARIFICATION]` marker so the reviewer fills the gap
during `/specify` review — the front door never silently invents content.

The rendered spec.md is engineered to satisfy validate_spec (Step 0) by construction when the Epic is
rich: §2 ordering signals, §4 data sources, §5 partner flags, §7 IF/THEN rules, §10 measurable criteria.
"""

from __future__ import annotations

from ingest.epic_models import EpicSignalLedger, LedgerSection

CLARIFY = (
    "[NEEDS CLARIFICATION — Epic did not state this; fill in during /specify review]"
)


def _provenance_header(ledger: EpicSignalLedger) -> str:
    p = ledger.provenance
    ov = p.object_version if p.object_version is not None else "unknown"
    return (
        "<!-- PROVENANCE: generated by /accelerator.ingest-epic (Phase A agentic shaping → "
        "Phase B deterministic mapping). DO NOT delete this header — /accelerator.refresh compares the "
        "Rally ObjectVersion below against Rally to detect epic drift. -->\n"
        f"> **Source:** Rally Epic `{p.formatted_id}` · **ObjectVersion** `{ov}`"
        f"{(' · updated ' + p.last_update_date) if p.last_update_date else ''}\n"
        "> Signal-bearing spec generated from the Epic. Review low-confidence sections (below) before "
        "`/plan`.\n"
    )


def _render_section(sec: LedgerSection) -> str:
    head = f"## §{sec.num}. {sec.title}"
    _shown = min(sec.filled, sec.expected_slots)
    _over = "+" if sec.filled > sec.expected_slots else ""
    conf = f"<!-- confidence {sec.confidence:.2f} (filled {_shown}{_over}/{sec.expected_slots}) -->"
    if not sec.signals:
        body = CLARIFY if not sec.optional else "_None stated in the Epic (optional)._"
        return f"{head}\n{conf}\n{body}\n"
    lines = [head, conf]
    for s in sec.signals:
        # §7 business rules render as IF/THEN bullets where the Epic phrased them that way.
        lines.append(f"- {s.value}")
    if sec.needs_review:
        lines.append(f"\n> {CLARIFY}")
    return "\n".join(lines) + "\n"


def map_ledger_to_spec(ledger: EpicSignalLedger) -> tuple[str, dict[str, float]]:
    """Render spec.md (str) + per-section confidence (dict). Deterministic — same ledger → same spec.md."""
    parts = [
        "# spec.md — Specification (generated from Rally Epic)",
        "",
        _provenance_header(ledger),
        "",
    ]
    for sec in ledger.sections:
        parts.append(_render_section(sec))
    # A compact confidence readout the prompt-file surfaces to the developer.
    parts.append(
        "<!-- PER-SECTION CONFIDENCE (signal-slot fill ratio; not an LLM self-assessment):"
    )
    for sec in ledger.sections:
        flag = "  REVIEW" if sec.needs_review else ""
        parts.append(f"     §{sec.num} {sec.title}: {sec.confidence:.2f}{flag}")
    parts.append("-->")
    spec_md = "\n".join(parts).rstrip() + "\n"
    return spec_md, ledger.per_section_confidence()
