# Per-agent Workload Identity service accounts.
# Constitution Rule 10: each agent gets ONLY the bindings for its assigned tools.
# Orchestrators (delegation-only) get NO direct data access.
# Generated by SDLC Accelerators (agentic-ai-adk domain skill).


# contract_review_loop (orchestrator — delegation only, no data access)

module "sa_contract_review_loop" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-contract-review-loop"
  display_name = "Agent SA — contract_review_loop"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
    "doc-store-mcp",
    "legal-review-a2a",
    "compliance-engine-a2a",
  ]
}

# extract_clauses

module "sa_extract_clauses" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-extract-clauses"
  display_name = "Agent SA — extract_clauses"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "doc-store-mcp:read",
    "clause_parser_fn:invoke",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
  ]
}

# legal_risk

module "sa_legal_risk" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-legal-risk"
  display_name = "Agent SA — legal_risk"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "legal-review-a2a:invoke",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
  ]
}

# compliance_risk

module "sa_compliance_risk" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-compliance-risk"
  display_name = "Agent SA — compliance_risk"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "compliance-engine-a2a:invoke",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
  ]
}

# synthesize_report

module "sa_synthesize_report" {
  source  = "github.com/company/tf-agent-identity"
  version = "v1.2.0"

  account_id   = "sa-synthesize-report"
  display_name = "Agent SA — synthesize_report"
  project_id   = var.project_id

  # Least-privilege capabilities (empty for delegation-only orchestrators).
  capabilities = [
    "report_builder_fn:invoke",
  ]

  # Explicitly denied tool bindings (defense in depth).
  denied_tools = [
  ]
}

