# Terraform for contract-review-assistant
# Generated by SDLC Accelerators (agentic-ai-adk domain skill).
# Constitution Rule 4: company modules ONLY — never raw google_*/aws_* resources.
# Constitution Rules 8-10: VPC-SC + CMEK + per-agent Workload Identity enforced by the modules.

terraform {
  required_version = ">= 1.5"
  required_providers {
    google = { source = "hashicorp/google", version = "~> 5.0" }
  }
}

variable "project_id" { type = string }
variable "env"        { type = string }


